src/main/java/uk/gov/hmcts/cmc/claimstore/models/otherparty/IndividualDetails.java
https://tools.hmcts.net/jira/browse/ROC-2046
Removed `@JsonUnwrapped` from dateOfBirth field. With this annotation it was not mapped from JSON.
```
[ ] Yes
[x] No
```
=> ROC-2046: removed @JsonUnwrapped from dateOfBirth field

src/main/resources/staff/templates/document/legalSealedClaim.html
https://tools.hmcts.net/jira/browse/ROC-2463
This PR fixes the bug for 'Service address' Label is missing for defendant 3 onwards
if they use same service address
```
[ ] Yes
[x] No
```
=> Fix label for service address

src/main/java/uk/gov/hmcts/cmc/claimstore/models/otherparty/TheirDetails.java, src/main/resources/db/migration/V2017_10_06_1624__Remove_empty_defendant_email_addresses.sql, src/test/java/uk/gov/hmcts/cmc/claimstore/models/TheirDetailsTest.java
https://tools.hmcts.net/jira/browse/ROC-2494
This PR does:
- make email address validation more strict to not allow empty values
- removes empty email address from defendant details
```
[ ] Yes
[x] No
```
=> ROC-2494: Forbid undefined email address

src/main/java/uk/gov/hmcts/cmc/claimstore/exceptions/CountyCourtJudgmentAlreadyRequestedException.java, src/main/java/uk/gov/hmcts/cmc/claimstore/exceptions/ResponseAlreadySubmittedException.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/DefendantResponseService.java, src/main/resources/staff/templates/document/legalSealedClaim.html, src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/DefendantResponseServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-2485
API blocked for saving response when response was already submitted for a claim or CCJ was requested.
```
[ ] Yes
[x] No
```
=> ROC-2485: blocked API from accepting response when CCJ was requested

src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandler.java
This will mean getting a 401 back from the claim store rather than a 500
if idam returns 401 say when the users token is expired
=> Pass along error codes from external API

build.gradle, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/BaseIntegrationTest.java, src/integrationTest/resources/environment.properties
None
This is to instantiate one database instance and run all the tests against that single instance. To avoid problems between tests runs caused by some database state tables are purged per test class.
Implementation is not ready for running tests in parallel however increasing threads executing tests right now does not bring any benefits due to the fact that by default spring tests are not ready for parallel run (that got fixed in Spring 5)
```
[ ] Yes
[x] No
```
=> Run integration tests in shared DB service

src/main/resources/application.yml
Requested by Mark F, there's a story (https://tools.hmcts.net/jira/browse/ROC-2727)
for changing it to 5 working days for potentially next sprint,
but Mark asked for the config change to happen first.
=> Change free mediation response deadline to 5 days

Dockerfile, docker/database/Dockerfile, src/integrationTest/resources/environment.properties
None
Use Alpine images in Dockerfiles and integration tests. That will speedup build process by tiny bit in case local cache is empty.
```
[ ] Yes
[x] No
```
=> Use Alpine images in Dockerfiles and integration tests

src/main/resources/citizen/templates/document/claimIssueReceipt.html, src/main/resources/citizen/templates/document/defendantResponseReceipt.html
https://tools.hmcts.net/jira/browse/ROC-2844
This PR fixes binding between interest content and templates so that data can be properly displayed.
```
[ ] Yes
[x] No
```
=> ROC-2844: Fix displaying interest on the claim issue receipt and defendant response receipt

build.gradle, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/DownloadRepresentedClaimCopyTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateClaimIssueReceiptTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateCountyCourtJudgementCopyTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateDefendantResponseCopyTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateDefendantResponseReceiptTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateSettlementAgreementCopyTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimWithCoreCaseDataStoreTest.java, src/main/java/uk/gov/hmcts/cmc/claimstore/config/JacksonConfiguration.java, src/main/java/uk/gov/hmcts/cmc/claimstore/config/PDFServiceConfiguration.java, src/main/java/uk/gov/hmcts/cmc/claimstore/config/ServiceTokenGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/cmc/claimstore/documents/CitizenSealedClaimPdfService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimIssueReceiptService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/documents/CountyCourtJudgmentPdfService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/documents/DefendantPinLetterPdfService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/documents/DefendantResponseCopyService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/documents/DefendantResponseReceiptService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/documents/LegalSealedClaimPdfService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/documents/SettlementAgreementCopyService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/healthcheck/PDFServiceHealthIndicator.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/cmc/claimstore/MockSpringTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/documents/CitizenSealedClaimPdfServiceTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/documents/DefendantResponseCopyServiceTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/documents/LegalSealedClaimPdfServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-1105
This change configures PDF Service client to use a HTTP client which has proper request tracing headers passing configured.
```
[ ] Yes
[X] No
```
=> ROC-1105: Configure new pdf service client

src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/SaveCoreCaseDataService.java
This PR removes the classification from `CaseDataContent` which was added by mistake.
```
[ ] Yes
[x] No
```
=> Remove classification from case data content

src/main/java/uk/gov/hmcts/cmc/claimstore/events/ccd/CoreCaseDataUploader.java
[ROC-3003](https://tools.hmcts.net/jira/browse/ROC-3003)
This PR fixes the scenario where save claim transaction rolls back but the CCD uploader event listener does not rolls back. The fix will invoke CCD uploader after commit of the transaction.
```
[ ] Yes
[x] No
```
=> ROC-3003: Call CCD save only if the transaction is committed

src/main/java/uk/gov/hmcts/cmc/claimstore/healthcheck/GovNotifyHealthIndicator.java
GOV Notify healthcheck was logging as a PDF service one.
```
[ ] Yes
[X] No
```
=> Fix an incorrect logging message

build.gradle
This restores stacktraces, they are slightly more verbose than before,
but all the information is there again
=> Bump java-logging version

src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/ClaimStore.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateCountyCourtJudgementCopyTest.java, src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java, src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CountyCourtJudgmentController.java, src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/PathPatterns.java, src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/ClaimRepository.java, src/main/java/uk/gov/hmcts/cmc/claimstore/rules/CountyCourtJudgmentRule.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/CountyCourtJudgmentService.java, src/test/java/uk/gov/hmcts/cmc/claimstore/rules/CountyCourtJudgmentRuleTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/CountyCourtJudgmentServiceTest.java
[ROC-3027](https://tools.hmcts.net/jira/browse/ROC-3027)
This PR refactors code for CCJ to use external id as identifier rather than database id. The frontend PR to accommodate the change is required.
Relevant pull request at `cmc-citizen-frontend` repo is: https://github.com/hmcts/cmc-citizen-frontend/pull/336
=> ROC-3027: Use external id as identifier rather than database id

src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GetClaimByClaimReferenceFromCoreCaseDataStoreTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GetClaimByExternalIdFromCoreCaseDataStoreTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GetClaimsByClaimantIdFromCoreCaseDataStoreTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimWithCoreCaseDataStoreTest.java, src/integrationTest/resources/environment.properties, src/main/java/uk/gov/hmcts/cmc/claimstore/services/search/CCDCaseRepository.java
This PR utilises the search results from CCD, when enabled. We were not using search results from CCD previously even it was turned on.
I have also tweaked some mock tests to make them green, as we are writing the functional tests later so will cover those later in detail.
=> ROC-3027: Turn on CCD searches

src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/AATConfiguration.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/Bootstrap.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/FunctionalTestsUsers.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/LinkDefendantTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/RequestCountyCourtJudgementTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/RespondToClaimTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SubmitClaimTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/TestData.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/idam/IdamTestService.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/smoke/RetrieveCaseTest.java, src/main/resources/application.yml
- renames environment variables used by automated tests,
- ensures functional tests claimant user is created only once for all functional tests.
```
[X] Yes
[ ] No
```
=> Rename env variables to be more intuitive

.gitignore, ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java, ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CaseEvent.java, ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/LinkDefendantTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/RespondToClaimTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SettlementOfferTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/idam/IdamTestService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java
Tests were failing on AAT because of the letter holder ID + 1, it was decided that we will save the letter holder and defendant ID now until a better CCD API is available
Spreadsheet changes:
https://github.com/hmcts/cmc-integration-tests/pull/153
=> ROC-3268 Save defendant and letter holder id

web.config
This allows hitting logstream via curl and just showing application logs
```
[timj@reformMgmtDevBastion02 ~]$ curl -k -utimja https://cmc-claim-store-aat.scm.service.core-compute-aat.internal/api/logstream/application
Enter host password for user 'timja':
2018-03-08T09:02:03  Welcome, you are now connected to log-streaming service.
2018-03-08T09:03:03  No new trace in the past 1 min(s).
2018-03-08T09:04:03  No new trace in the past 2 min(s).
AI: INFO 08-03-2018 09:04, 1: Configuration file has been successfully found as resource
AI: INFO 08-03-2018 09:04, 1: Configuration file has been successfully found as resource
```
https://github.com/projectkudu/kudu/wiki/Diagnostic-Log-Stream
Tested via modifying web.config in kudu
=> Fix logstream filtering

ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/HousingDisrepairMapper.java
This PR fixes the NullPointerException which occurs when user selects HousingDisrepair and no other damages are claimed.
> claim-store-api_1                      | Caused by: java.lang.NullPointerException: Name is null
claim-store-api_1                      |     at java.lang.Enum.valueOf(Enum.java:236)
claim-store-api_1                      |     at uk.gov.hmcts.cmc.domain.models.particulars.DamagesExpectation.valueOf(DamagesExpectation.java:5)
claim-store-api_1                      |     at uk.gov.hmcts.cmc.ccd.mapper.HousingDisrepairMapper.from(HousingDisrepairMapper.java:26)
claim-store-api_1                      |     at uk.gov.hmcts.cmc.ccd.mapper.ClaimMapper.from(ClaimMapper.java:125)
claim-store-api_1                      |     at …
=> Fix NullPointerException

domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Payment.java, src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimDataContentProvider.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/DefendantPinLetterContentProvider.java
https://tools.hmcts.net/jira/browse/ROC-3059
Amount value from payment object now will contain either pennies or pounds. We cannot relay on it anymore and it will be removed in the future completely. Instead we should relay on `ClaimData#feeAmountInPennies` which can be transformed into pounds. That PR uses `feeAmountInPennies` for PDF's
```
[ ] Yes
[x] No
```
=> Stop using payment amount from payment object as it is deprecated

src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
Before it was outputting null because reference number isn't set at that point
=> Fix save claim failed log message

src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/RequestCountyCourtJudgementTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/RespondToClaimTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SettlementOfferTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SubmitClaimTest.java
We've noticed quite high delays on AAT environment (~40 seconds), relaxing time related assertions to accommodate for this.
```
[ ] Yes
[X] No
```
=> Relax time assertions

src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/RootTest.java, src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/RootController.java
Application insights was registering lots of failures because of the
azure keep alive which hits the app every 5 seconds on / (its not
configurable)
=> Remove 404 from root

src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimDataContentProvider.java
This PR fixes the below error in case no evidence was provided.
```
claim-store-api_1                      | 2018-03-20T13:45:22.921+0000 ERROR [http-nio-4400-exec-2] uk.gov.hmcts.cmc.claimstore.controllers.advices.ResourceExceptionHandler:41: null
claim-store-api_1                      |     at uk.gov.hmcts.cmc.claimstore.documents.ClaimDataContentProvider.createContent(ClaimDataContentProvider.java:72)
claim-store-api_1                      |     at uk.gov.hmcts.cmc.claimstore.documents.ClaimContentProvider.createContent(ClaimContentProvider.java:58)
claim-store-api_1
```
=> Fix error when evidence is not provided

src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/InterestContentProvider.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/InterestProviderTest.java
This happens when issue date is in the future
Prevents empty field from showing in the pdf amount total section
=> Set interest to 0 if not calculating

domain-model/src/main/java/uk/gov/hmcts/cmc/domain/utils/LocalDateTimeFactory.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/RequestCountyCourtJudgementTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/RespondToClaimTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SettlementOfferTest.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SubmitClaimTest.java
Builds are currently failing on jenkins during functional tests because of the DST change
=> Use UTC for checking timestamps

src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/services/citizen/SettlementReachedCitizenNotificationTest.java
That test has shown to be flaky on all kinds of environments (Jenkins, Travis, local). I removed all the assumptions on the total number of `sendEmail` invocations, hopefully this should resolve the problem. I ran the test a number of times on my local and haven't seen it fail so far.
```
[ ] Yes
[X] No
```
=> Cleanup counter sign notifications test

docker-compose.yml
https://tools.hmcts.net/jira/browse/ROC-3525
HMCTS org is now available, using that instead
```
[ ] Yes
[ ] No
```
=> ROC-3535 Update to hmcts org for dockerhub

domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/ClaimantAmountConstraintValidator.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/DateNotInTheFutureConstraintValidator.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/DateNotInThePastConstraintValidator.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/FutureDateConstraintValidator.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/PhoneNumberConstraintValidator.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/ValidCountyCourtJudgmentValidator.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/ValidInterestConstraintValidator.java
After updating the validator framework, we don't need to override empty `initialize` method as it comes with default in `ConstraintValidator` interface.
=> Remove empty initilize methods from validators

ccd-adapter/build.gradle, domain-model/build.gradle
This PR replaces the deprecated `apt` configuration with `annotationProcessor`, as apt is deprecated.
```
[ ] Yes
[x] No
```
=> Replace apt deprecated configuration

Dockerfile
wget was trying to download 'health' from 'http://localhost:4400/health' and failing, leading to an unhealthy container.
By using the --spider command, we check for a 200 response instead. 
```
[ ] Yes
[x] No
```
=> BigFix: Fixed unhealthy claim-store container

README.md
The section in the README explaining how to connect to the database from within the claim-store is no longer relevant.
=> Removed outdated section in the README

Dockerfile, docker-compose.yml
Most of the local docker build was spent waiting for the build context to be sent to the docker daemon, that took awhile because of the large file size of all the jars in the context we were sending, I've restricted it down to only the directory with the jar in it, sample of large files before:
```
$ find . -type f -exec du -a {} + | sort -n -r | less
163856  ./ccd-claim-migration/build/distributions/ccd-claim-migration-1.1.0.tar
134816  ./build/distributions/claim-store-boot-1.1.0.tar
131088  ./build/distributions/claim-store-1.1.0.tar
131080  ./build/libs/claim-store.jar
122888  ./ccd-claim-migration/build/distributions/ccd-claim-migration-1.1.0.zip
116744  ./build/distributions/claim-store-boot-1.1.0.zip
116744  ./build/distributions/claim-store-1.1.0.zip
69648 …
```
=> Much faster docker build locally

src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/FormaliseResponseAcceptanceService.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/FormaliseResponseAcceptanceServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-4415
This PR makes call to finalise method only when finalise option is provided.
Additionally small refactoring was made to make finalise method accept only certain responses.
```
[ ] Yes
[x] No
```
=> ROC-4415: Finalise claimant response only when finalise option is provided

domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/ResponseRejection.java, domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/ResponseRejectionTest.java, domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimantResponse.java, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ClaimantResponseTest.java
[ROC-4413](https://tools.hmcts.net/jira/browse/ROC-4413)
This PR makes adds `reason` optional for `ResponseRejection` with max char limit of 99k
=> ROC-4413: Add reason for states paid claimant response

src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseService.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseServiceTest.java
[ROC-4413](https://tools.hmcts.net/jira/browse/ROC-4413)
This PR fixes the issue where event was generated before preserving the data in repository.
=> Generate event once claimant response successfully saved

dependency-check-suppressions.xml, infrastructure/main.tf
Cleanup post SIDAM testing. The pipeline failed once reverted changes at apply stage. I added this dummy value to ensure the next pipeline run would re-apply! There was a case before where state was out of sync - I think when this sequence of events happen:
--> SIDAM changes to terraform --> plan --> apply --> all good
--> Revert --> plan --> apply X failed (but state has been updated with reverted values, but deployment still has SIDAM changes
--> If we make no changes to terraform --> apply thinks no changes so essentially skips - this is why we need the forced apply with a dummy setting.
```
[ ] Yes
[ X ] No
```
=> ROC-4719: remove dummy app_setting

src/main/resources/db/migration/claimstore/V2018_11_28_1148__Define_directions_questionnaire_deadline_for_full_defence.sql
https://tools.hmcts.net/jira/browse/ROC-4836
Add migration script to populate the `directions_questionnaire_deadline` column of the `claims` table when a full defence has been submitted and the column is still `NULL`
```
[ ] Yes
[x] No
```
https://github.com/hmcts/cmc-citizen-frontend/pull/1189
=> ROC-4836 full defence directions questionnaire deadlines migration

src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java, src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/DBCaseRepository.java
A quick fix for our broken dockerhub builds:
```> Task :compileJava
[91m/home/gradle/src/src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java:4: error: package org.apache.commons.lang does not exist
import org.apache.commons.lang.StringUtils;
^
/home/gradle/src/src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/DBCaseRepository.java:3: error: package org.apache.commons.lang does not exist
import org.apache.commons.lang.StringUtils;
^
[0m
[91m2 errors
[0m
> Task :compileJava FAILED```
```
[ ] Yes
[ X ] No
```
=> fix dockerhub builds

src/test/java/uk/gov/hmcts/cmc/claimstore/rules/ClaimantResponseRuleTest.java
Sonar failing with 79.92% coverage - I'm hoping this will push us past 80%. Worth a visit to see where we are lacking: https://sonarcloud.io/dashboard?id=uk.gov.hmcts.cmc%3Aclaim-store
[ ] Yes
[ X ] No
=> ROC-4520: increase unit test coverage

ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/claimantresponse/CourtDeterminationMapper.java, ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/ClaimantResponseMapperTest.java
This PR cleans up few unit tests and refactors the code. Below are the items cleaned.
1. In `ClaimantResponseMapperTest.java`, these kind of conditions in tests are wrong, because if the condition is false assertion will not be called at all. And test may pass incorrectly.
```
if (claim.getClaimantResponse().isPresent()) {
assertThat((ResponseAcceptation) claim.getClaimantResponse().get()).isEqualTo(ccdResponse);
}
```
2. In `CourtDeterminationMapper.java` unnecessary `null` check.
```
if (ccdCourtDetermination.getRejectionReason() != null) {
builder.rejectionReason(ccdCourtDetermination.getRejectionReason());
}
```
3. Unnecessary unwrapping of `Optionals`
e.g. 
```
assertNotNull(claim.getClaimantRespondedAt().orElse(null));
```
**Does this PR introduce a breaking change?** (check one …
=> Refactor and cleanup tests

src/main/java/uk/gov/hmcts/cmc/claimstore/services/SettlementAgreementService.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/SettlementAgreementServiceTest.java
[ROC-5116](https://tools.hmcts.net/jira/browse/ROC-5116)
This PR fixes the bug, where countersign settlement agreement was not saving the timestamp.
=> ROC-5116: Save timestamp for countersign settlement

src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/BaseSubmitClaimTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimTest.java, src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsightsEvent.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-5104
When saving a claim whose external ID is already found in the claim-store, raise a new app insights event (`Claim attempt - Duplicate` with the external ID) and proceed with the claim creation event as usual.
```
[ ] Yes
[x] No
```
=> ROC-5104 Proceed with claim creation events when external ID already found in claim store

dependency-check-suppressions.xml
Suppress dependency check - irrelevant as specific to XML processing:
```
> Task :dependencyCheckAnalyze
Verifying dependencies for project claim-store
Checking for updates and analyzing dependencies for vulnerabilities
Generating report for project claim-store
Found 2 vulnerabilities in project claim-store
One or more dependencies were identified with known vulnerabilities:
javax.json-api-1.1.4.jar: ids:(javax.json:javax.json-api:1.1.4, cpe:/a:processing:processing:1.1.4) : CVE-2018-1000840
javax.json-1.1.4.jar: ids:(org.glassfish:javax.json:1.1.4, cpe:/a:processing:processing:1.1.4) : CVE-2018-1000840
```
```
[ ] Yes
[ x ] No
```
=> Suppress dependency check error: CVE-2018-1000840

src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/PartAdmissionResponseContentProvider.java, src/main/resources/citizen/templates/document/defendantResponseReceipt.html, src/test/java/uk/gov/hmcts/cmc/claimstore/documents/content/PartAdmissionResponseContentProviderTest.java
https://tools.hmcts.net/jira/browse/ROC-5179
Fix defendant response PDF issue where the payment intention section would not be shown when present.
```
[ ] Yes
[x] No
```
=> ROC-5179 - Missing Instalment amount and financial details In Defendant Response PDF

Jenkinsfile_CNP
Platform changed some infrastructure code that meant git commands were over https and not ssh anymore, this broke the force push to demo.
Also some cleanup of CCD migration comments - no longer required.
```
[ ] Yes
[ x ] No
```
=> Fix push to use https git repo

charts/cmc-claim-store/Chart.yaml, charts/cmc-claim-store/values.template.yaml
Importing this chart into frontend breaks - tags are ignored and claim-store frontend is initialised too.
E.g. https://github.com/hmcts/cmc-citizen-frontend/blob/3d8f7c10d5e2915ab4ac6d61c4fba4d8d05e462d/charts/cmc-citizen-frontend/values.template.yaml#L86  - doesnt have any effect :(
```
[ ] Yes
[ x ] No
```
=> Fix helm tags

src/main/java/uk/gov/hmcts/cmc/claimstore/config/CCDStoreConfiguration.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CCDCreateCaseService.java
```***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 7 of method coreCaseDataService in uk.gov.hmcts.cmc.claimstore.config.CCDStoreConfiguration required a bean of type 'uk.gov.hmcts.cmc.claimstore.services.ccd.CCDCreateCaseService' that could not be found.
Action:
Consider defining a bean of type 'uk.gov.hmcts.cmc.claimstore.services.ccd.CCDCreateCaseService' in your configuration.
```
```
[ ] Yes
[x] No
```
=> Fixes to sort application not starting

charts/cmc-claim-store/Chart.yaml, charts/cmc-claim-store/requirements.yaml, charts/cmc-claim-store/values.template.yaml
Helm tags need defining at top level values. This means we need to use app specific tags for generic services like database. Tested locally with `helm template`.
```
[ ] Yes
[ x ] No
```
=> Fix helm tagging

Jenkinsfile_CNP, charts/cmc-claim-store/values.template.yaml, infrastructure/aat.tfvars, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/idam/IdamTestService.java
SIDAM doesnt allow unencoded values like: `civilmoneyclaims+mAueB1l5Gk%40gmail.com`. This fix encodes email param first.
This should be backward compatible for TIDAM.
Tested locally.
```
[ ] Yes
[x] No
```
=> SIDAM code freeze - changes for AAT

ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CaseEvent.java, ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/legaladvisor/CCDOrderDirectionType.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateOrderCallbackTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/MoreTimeRequestedCallbackTest.java, src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CallbackController.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/CallbackService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/LegalOrderGenerationDeadlinesCalculator.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/CallbackServiceTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/LegalOrderGenerationDeadlinesCalculatorTest.java
https://tools.hmcts.net/jira/browse/ROC-5477
Adding a about to start callback to the generate order event, to prepopulate the doc upload deadline, the eyewitness upload deadline and the direction list (all selected).
In other PRs I might move those callback-specific methods out of the ClaimService (which is doing too many things) into the CallbackService.
```
[ ] Yes
[x] No
```
=> ROC-5477 Prepopulate fields for GenerateOrder callback

src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/ClaimOperation.java
Bumped up the retires count and cleanup code.
=> Optimise retries for get by letter holder id in functional tests

domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/metadata/PartyStatementMetadata.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/metadata/SettlementMetadata.java
https://tools.hmcts.net/jira/browse/ROC-5863
New metadata class for party statements that does not include the settlement offer content free-text
```
[ ] Yes
[x] No
```
=> ROC-5863 Ignore free-text settlement data

Dockerfile, src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/StatementOfMeansContentProvider.java, src/test/java/uk/gov/hmcts/cmc/claimstore/documents/content/StatementOfMeansContentProviderTest.java
https://tools.hmcts.net/jira/browse/ROC-5964
Distinguish between "Retired" and other unemployed job states in the defendant response PDF.
```
[ ] Yes
[x] No
```
=> ROC-5964 Defendant response PDF to show "Retired" when appropriate

dependency-check-suppressions.xml
Already suppressed in multiple hmcts github repos. E.g. https://github.com/hmcts/java-logging/blob/2accf8b06b47a19a8412e834e0cb56a1b5445510/config/owasp/suppressions.xml
```
[ ] Yes
[x] No
```
=> Suppress CVE-2019-12814

dependency-check-suppressions.xml
Suppress CVE-2019-14540 and CVE-2019-16335 from dependency checks as they do not seem to be exploitable and will be patched in an upcoming jackson release.
=> Suppression of CVEs

domain-model/src/test/resources/claim-application.json, domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SamplePayment.java, src/test/resources/claim-application.json
Adding next url to the payment has to yet be released in ccd, so functional tests (which seem to rely on the default builder) don't like this.
=> Remove next url from SamplePayment

src/main/resources/citizen/templates/document/claimIssueReceipt.html, src/main/resources/citizen/templates/document/claimantResponseReceipt.html, src/main/resources/citizen/templates/document/defendantResponseReceipt.html, src/main/resources/staff/templates/document/defendantPinLetter.html, src/main/resources/staff/templates/document/legalOrderCoverSheet.html, src/main/resources/staff/templates/document/legalSealedClaim.html, src/main/resources/staff/templates/document/sealedClaim.html, src/main/resources/staff/templates/document/settlementAgreement.html, web.config
https://tools.hmcts.net/jira/browse/ROC-6005
Encode right single quotes we're using for apostrophe's in html templates
=> ROC-6005 Encode pretty apostrophes as `&#8217;`

src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportController.java, src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportControllerTest.java
https://tools.hmcts.net/jira/browse/ROC-6699
Update support endpoint for uploading documents to DM to:
* allow anonymous invocation (use anonymous caseworker)
* report different statuses according to if anything was actually done
200 = the document was already there
201 = a new document was generated and uploaded
4xx for errors according to the relevant service
=> ROC-6699 Update support controller for DM uploads

domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/metadata/CaseMetadata.java, src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/CaseMetadataControllerTest.java
https://tools.hmcts.net/jira/browse/ROC-6725
Case Metadata structure assumed 1 claimant and 1 defendant, but legal-rep claims can already have multiples of either and both. This PR modifies the class to support multiple claimants and multiple defendants.
=> ROC-6725 Update metadata structure to support multi-party (for LR)

charts/cmc-claim-store/values.preview.template.yaml
Nodejs10 requires more memory to run. This was already done in citizen-frontend:
https://github.com/hmcts/cmc-citizen-frontend/blob/master/charts/cmc-citizen-frontend/values.yaml#L4-L5
```
[ ] Yes
[x ] No
```
=> increase memory for nodejs

build.gradle
=> Bump quartz version because of CVE-2019-13990

ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java, ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/ClaimMapper.java, ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/ClaimAssert.java, ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapperTest.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Claim.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/metadata/CaseMetadata.java, domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaim.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/CreateClaimCitizenTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/InitiatePaymentTest.java, src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/ResumePaymentTest.java, src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java, src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/PostClaimOrchestrationHandler.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java, src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimControllerTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/PostClaimOrchestrationHandlerTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDetailsConverterTest.java
https://tools.hmcts.net/jira/browse/ROC-6127
As part of IOC we need to check the claim status (in ccd) from the frontend, so we need to serialise it back as part of the claim
```
[ ] Yes
[x] No
```
=> ROC-6127 Serialise claim state and remove submitter id from ioc endpoints

domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/RepaymentPlan.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/CourtDetermination.java, domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/response/PaymentIntention.java, domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/response/PaymentIntentionTest.java
https://tools.hmcts.net/jira/browse/ROC-7063
Add validation groups to disable the constraint that the first repayment date cannot be in the past when responding to the proposal
=> ROC-7063 Allow accepting repayment plans starting in the past

src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/rpa/RequestForJudgementNotificationServiceTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DeadlineSupportControllerTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/events/DocumentUploadHandlerTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/PostClaimOrchestrationHandlerTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/events/claimantresponse/ClaimantResponseStaffNotificationHandlerTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/FormaliseResponseAcceptanceServiceTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/DefendantResponseNotificationServiceTest.java
After bumping up the mockito version, we have `verifyZeroInteractions` deprecated. It's recommended to use `verifyNoInteractions` instead.
=> Upgrade the mockito deprecated method

build.gradle, src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/deprectaed/MockedDatabaseConfiguration.java
Move mocked configuration in aat as not required for integration tests
```
[ ] Yes
[ ] No
```
=> ROC-6843: Move mocked configuration in aat as not required for integration tests

src/main/java/uk/gov/hmcts/cmc/claimstore/config/CmcDBConfiguration.java
https://tools.hmcts.net/jira/browse/ROC-7508
1. To solve it a solution on flyway doc to set the
baselineOnMigrate to true.
=> ROC-7508-Flyway fails on migrate unable to find flyway_schema_history table

build.gradle, src/main/java/uk/gov/hmcts/cmc/claimstore/config/CmcDBConfiguration.java
https://tools.hmcts.net/jira/browse/ROC-7508
Revert the flyway upgrade to avoid hassles with the migration strategy thats required for the upgrade from 5.4.2 to 6.2.2
=> ROC-7508-Flyway revert version upgrade to unblock pipeline

src/main/java/uk/gov/hmcts/cmc/claimstore/events/response/DefendantResponseStaffNotificationHandler.java
https://tools.hmcts.net/jira/browse/ROC-7378
https://tools.hmcts.net/jira/browse/ROC-7379
Added a feature toggle to turn on/off the staff emails in case of full admission/part admission/full defence.
=> Feature/ROC-7378 and ROC-7379 feature toggle added for staff email full admission/part admission/full defence

src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseService.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-7916
This is a fix  for if opted out for new feature, claimant rejection for FullDefence, No Mediation, should update DQDeadline and the claimant response submission should not fail with a 409.
=> ROC-7916 - Fix for claimant rejection for FullDefence, No Mediation, Offline DQ throws 409 exception

ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/PaymentMapper.java
This PR adds null check in to mapper as payment is not being sent from frontend after IOC
=> ROC-7890: Add null check for payment status in mapper

build.gradle, charts/cmc-claim-store/Chart.yaml, charts/cmc-claim-store/values.preview.template.yaml, charts/cmc-claim-store/values.yaml, infrastructure/main.tf, launch-darkly-client/build.gradle, launch-darkly-client/src/main/java/uk/gov/hmcts/cmc/launchdarkly/LaunchDarklyClient.java, launch-darkly-client/src/main/java/uk/gov/hmcts/cmc/launchdarkly/internal/LDClientFactory.java, launch-darkly-client/src/test/java/uk/gov/hmcts/cmc/launchdarkly/LaunchDarklyClientTest.java, launch-darkly-client/src/test/java/uk/gov/hmcts/cmc/launchdarkly/internal/LDClientFactoryTest.java, settings.gradle, sonarlint, src/main/java/uk/gov/hmcts/cmc/claimstore/healthcheck/LaunchDarklyHealthIndicator.java, src/main/resources/application.yml, src/main/resources/bootstrap.yml, src/test/java/uk/gov/hmcts/cmc/claimstore/healthcheck/LaunchDarklyHealthIndicatorTest.java
https://tools.hmcts.net/jira/browse/ROC-8014
Integrate LaunchDarkly into the claim-store. Add a temporary health indicator revealing the state of a temporary toggle, for testing purposes.
Clean-up PR: https://github.com/hmcts/cmc-claim-store/pull/1714
=> ROC-8014 Add LaunchDarkly integration

ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java, ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapperTest.java
https://tools.hmcts.net/jira/browse/ROC-8002
The preferred court was missing for the cases where mediation has taken place.
That has been fixed now.
=> ROC-8002 | fixing missing preferred court

build.gradle, job-scheduler/build.gradle
N/A
Upgrade Postgres JDBC Driver to 42.2.14 to fix known vulnerability (CVE-2020-13692)
=> Upgrade Postgres JDBC Driver to 42.2.14

src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/rules/GenerateOrderRule.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/rules/GenerateOrderRuleTest.java
https://tools.hmcts.net/jira/browse/ROC-8454
Null check has been added as part of validation for the optional date fields
=> Judges direction order - null pointer fix

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/ROC-8577
Suppressed dependency error CVE-2020-13956 caused by http-client
=> ROC-8577-Nightly-build-Dependency-error-suppressed

src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportController.java, src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDElasticSearchRepository.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/MediationCSVGenerator.java, src/main/java/uk/gov/hmcts/cmc/claimstore/services/MediationReportService.java, src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportControllerTest.java, src/test/java/uk/gov/hmcts/cmc/claimstore/services/MediationReportServiceTest.java
File name reflecting mediation report date (reflect the date for which the file contains the details) - if it triggered for 6th Feb's report on 10th Feb, filename should be MediationCSV.06-02-2021
Email subject and message will reflect the mediation report date.
Email address - Report can be shared with specific email address on request via support controller
Log statements - to find out how many claims are retrieved from DB via elastic search - this change will confirm the issue with elastic search process.
More log statements for similar exceptions on the process - to help in debugging any further issue.
https://tools.hmcts.net/jira/browse/ROC-8864
=> MILO report fix

src/main/java/uk/gov/hmcts/cmc/claimstore/services/UserService.java
Removing this `authenticateUserCache ` as both of the methods called inside`authenticateUser` have cache enabled for those. So this is not needed. And this is causing errors on AAT while running the tests.
=> Remove unnecessary cache
