hmcts/cmc-claim-store

- src/main/java/uk/gov/hmcts/cmc/claimstore/models/Address.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/AddressTest.java
https://tools.hmcts.net/jira/browse/ROC-2226
City is mandatory field
```
[y] Yes
[ ] No
```
> ROC-2226: city is mandatory field

- src/main/java/uk/gov/hmcts/cmc/claimstore/models/ClaimData.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/utils/sampledata/SampleClaimData.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/ClaimDataTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/sampledata/SampleTheirDetails.java
https://tools.hmcts.net/jira/browse/ROC-2150
This PR updated the allowed defendants limit to 20.
```
[ ] Yes
[x] No
```
> Update defendants limit

- src/main/java/uk/gov/hmcts/cmc/claimstore/models/otherparty/CompanyDetails.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/models/otherparty/IndividualDetails.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/models/otherparty/OrganisationDetails.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/models/otherparty/SoleTraderDetails.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/models/otherparty/TheirDetails.java
- src/main/resources/staff/templates/document/legalSealedClaim.html
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/SerializationTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/TheirDetailsTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/sampledata/SampleTheirDetails.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/processors/JsonMapperTest.java
- src/test/resources/legal-claim-application.json
Reverts hmcts/cmc-claim-store#7
Reverting this as it is breaking claim submission. Needs proper testing before making into master.
> Revert "ROC-1777 Add in service address for defendants"

- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/models/DefendantDetailsContent.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/models/ResponseData.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/ClaimContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/models/ClaimContent.java
- src/main/resources/staff/templates/document/defendantResponseCopy.html
- src/main/resources/staff/templates/document/sealedClaim.html
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/utils/sampledata/SampleResponseData.java
https://tools.hmcts.net/jira/browse/ROC-2332
Capture defendant contact person and position for SOT
```
[ ] Yes
[ X] No
```
> ROC-2332: Update SOT for claimant/defendant type company and organisation

- src/main/resources/staff/templates/document/legalSealedClaim.html
This PR implements the review comment.
```
[ ] Yes
[x] No
```
> Implement code review comments

- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CountyCourtJudgmentController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/models/ccj/RepaymentPlan.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/CountyCourtJudgmentService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/CountyCourtJudgmentServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-2046
Using CCJ model in controller
```
[ ] Yes
[x] No
```
> ROC-2046: using CCJ model in controller and  service

- src/main/resources/staff/templates/document/legalSealedClaim.html
https://tools.hmcts.net/jira/browse/ROC-2378
add defendants address to service address on pdf if no service address has been included. 
```
[ ] Yes
[X] No
```
> ROC-2378 - update to include defendants address as service address

- src/main/resources/staff/templates/document/legalSealedClaim.html
remove apostrophe to stop wrapping on pdf
```
[ ] Yes
[ ] No
```
> Bug - remove apostrophe to fix wrapping issue

- src/main/resources/staff/templates/email/ccjRequestSubmitted/body.txt
- src/main/resources/staff/templates/email/ccjRequestSubmitted/subject.txt
https://tools.hmcts.net/jira/browse/ROC-2048
CJ request submitted email content change
```
[ ] Yes
[x ] No
```
> ROC-2048 CCJ request submitted email content change

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/CCJRequestedNotificationService.java
- src/main/resources/staff/templates/document/countyCourtJudgmentDetails.html
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/CCJRequestedNotificationServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-2468
Add claimant declaration in ccj details pdf
```
[ ] Yes
[ x] No
```
> ROC-2468 Add claimant declaration in ccj details pdf

- src/test/java/uk/gov/hmcts/cmc/claimstore/events/CCJRequestedCitizenActionsHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-2494
Improved unit test
```
[ ] Yes
[x] No
```
> ROC-2494: fixed unit test condition

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/CCJStaffNotificationServiceTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/models/CCJContent.java
- src/main/resources/staff/templates/document/countyCourtJudgmentDetails.html
https://tools.hmcts.net/jira/browse/ROC-2057
Add claimant name and ccj request date to ccj pdf
```
[ ] Yes
[ x] No
```
> ROC-2057 Add signerName and signerRole to ccj pdf

- src/main/resources/staff/templates/email/ccjRequestSubmitted/body.txt
None
Changes highlighted during feature review.
```
[ ] Yes
[x] No
```
> Add extra line to the CCJ staff notification email after content review

- src/main/java/uk/gov/hmcts/cmc/claimstore/models/CountyCourtJudgment.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/models/CCJContent.java
- src/main/resources/db/migration/V2017_10_13_1133__Remove_defendant_details_from_CCJ.sql
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/sampledata/SampleCountyCourtJudgment.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/serialization/CountyCourtJudgmentSerializationTest.java
- src/test/resources/county-court-judgment/by-instalments.json
https://tools.hmcts.net/jira/browse/ROC-2567
Changes are based on changes coming on https://github.com/hmcts/cmc-claim-store/pull/56.
If someone wants to review it makes sense to have a look at last commit otherwise all changes are visible.
```
[x] Yes
[ ] No
```
> ROC-2567: Remove defendant details form CCJ domain

- .editorconfig
- build.gradle
- config/checkstyle/checkstyle.xml
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveRepresentativeClaimTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/constraints/MinTotalAmountValidatorTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/SoleTraderTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/sampledata/SampleInterestDate.java
This upgrade also fixes warnings not failing the build on
integrationTest sources for some reason
> Upgrade checkstyle

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/MakeOfferTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/OfferMadeCitizenActionsHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/OfferMadeNotificationService.java
https://tools.hmcts.net/jira/browse/ROC-2473
Fixed bug, added tests
```
[ ] Yes
[x] No
```
> ROC-2473: fixed logic and added more tests

- src/main/resources/staff/templates/document/legalSealedClaim.html
https://tools.hmcts.net/jira/browse/ROC-2289
This PR adds Claim number in headers from second page onwards.
```
[ ] Yes
[x] No
```
> Add claim number in top header

- src/main/java/uk/gov/hmcts/cmc/claimstore/idam/models/GeneratePinResponse.java
Fridam returns some properties we don't care about, ignore them
```
{"pin":"VWY0IT3I","expiry":"1519727973134","userId":"39574e6c-8fb1-40a0-a82a-dbfe2b5f1860","roleId":"1fafb9c7-4bd2-40c6-af2c-aebafb29ba88"}
```
> Ignore unknown idam properties

- Jenkinsfile
https://tools.hmcts.net/jira/browse/ROC-2432
Use open-sourced IT project to run @quick test suite.
```
[ ] Yes
[X] No
```
> ROC-2432: Use open-sourced IT project to run @quick test suite

- Jenkinsfile
Reverts hmcts/cmc-claim-store#82
> Revert "Disable automatic deployment to DEMO env"

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/AcceptOrRejectOfferTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/OfferAcceptedEvent.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/OfferRejectedEvent.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/OfferRespondedEvent.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/models/offers/Settlement.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/OffersService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/models/offers/SettlementTest.java
https://tools.hmcts.net/jira/browse/ROC-2476
Refactoring
```
[ ] Yes
[x] No
```
> ROC-2476: code refactored according to code review comments

- cmc-domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/offers/Settlement.java
- cmc-domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/offers/SettlementTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/SupportController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/settlementagreement/SettlementAgreementPDFContentProvider.java
- src/main/resources/staff/templates/document/settlementAgreement.html
https://tools.hmcts.net/jira/browse/ROC-2477
> ROC-2477 Add template

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/ClaimMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapperTest.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/ClaimMapperTest.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/CompanyMapperTest.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/IndividualMapperTest.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/OrganisationMapperTest.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/PartyMapperTest.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/SoleTraderMapperTest.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/util/SampleData.java
https://tools.hmcts.net/jira/browse/ROC-2903
This PR adds mapping of CCD case to CMC claim.
```
[ ] Yes
[x] No
```
> ROC-2903: Mapper from CCD case to CMC claim

- build.gradle
ignore domain models from code coverage
```
[ ] Yes
[x] No
```
> Ignore domain models from sonar code coverage

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/utils/PartyUtils.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/utils/PartyUtilsTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/SealedClaimContentProvider.java
https://tools.hmcts.net/jira/browse/ROC-2844
This is refactoring to make future development easier.
```
[ ] Yes
[x] No
```
> ROC-2844: Rename methods and arguments in PartyUtils to make these more generic

- src/main/resources/staff/templates/document/legalSealedClaim.html
https://tools.hmcts.net/jira/browse/ROC-2927
Add sole trader option to PDF
```
[ ] Yes
[X] No
```
> ROC-2719 add in sole trader content

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/FullDefenceResponse.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Response.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/ResponseTest.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleResponse.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateDefendantResponseCopyTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateSettlementAgreementCopyTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ResendStaffNotificationsTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveDefendantResponseTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/DefendantResponseCopyContentProvider.java
- src/main/resources/db/migration/V2017_12_08_1132__Prepare_response_structure_for_subclassing.sql
- src/main/resources/staff/templates/email/defendantResponse/body.txt
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/DefendantResponseControllerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/content/DefendantDetailsContentProviderTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/content/DefendantResponseCopyContentProviderTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/content/DefendantResponseStaffNotificationEmailContentProviderTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/DefendantResponseStaffNotificationServiceTest.java
- src/test/resources/defendant-response.json
[ROC-2703](https://tools.hmcts.net/jira/browse/ROC-2703)
Introduce FullDefenceResponse as (the only, as of now) subtype of
Response, and use it in place of Response.
```
[x] Yes
[ ] No
```
> ROC-2703: Introduce FullDefenceResponse

- Jenkinsfile
> CMC Claimstore Jenkins build to influx 

- build.gradle
https://tools.hmcts.net/jira/browse/ROC-1105
Update to latest java-logging version.
```
[ ] Yes
[X] No
```
> ROC-1105: Update Java logging version

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimWithCoreCaseDataStoreTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/ClaimStoreApplication.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/ccd/CoreCaseDataUploader.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/SaveCoreCaseDataService.java
- src/main/resources/application.yml
Use updated CCD client and let ccd client initialise itself.
```
[ ] Yes
[X] No
```
> Use updated CCD client

- Jenkinsfile
- build.gradle
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/DownloadRepresentedClaimCopyTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/DownloadRepresentedClaimCopyWithDocumentManagementTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ResendStaffNotificationsTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimWithCoreCaseDataStoreTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimWithDocumentManagementTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/ClaimStoreApplication.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/DocumentUploader.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/AlwaysGenerateDocumentsService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementBackedDocumentsService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementService.java
- src/main/resources/application.yml
[ROC-2984](https://tools.hmcts.net/jira/browse/ROC-2984)
Use of updated document management client.
```
[ ] Yes
[x] No
```
> ROC-2984: Use updated DM client

- Jenkinsfile
This PR tests the fix for influx db changes.
```
[ ] Yes
[x] No
```
> Un comment influx db publisher

- src/main/resources/db/migration/V2018_01_12_1645__Merge_title_and_name_for_individuals.sql
[ROC-2926](https://tools.hmcts.net/jira/browse/ROC-2926)
This PR fixes the typo in script to combine title and name fields.
```
[ ] Yes
[x] No
```
> ROC-2926: Fix typo in script

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ResponseDeadlineCalculator.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ResponseDeadlineCalculatorTest.java
[ROC-3089](https://tools.hmcts.net/jira/browse/ROC-3089)
This PR changes the calculation for response deadline based on calendar days rather than on working days. 
> ROC-3089: Calculate response deadline based on calendar days

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ResponseDeadlineCalculator.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ResponseDeadlineCalculatorTest.java
Reverts hmcts/cmc-claim-store#153
As per business requirements, after discussion with Art & Clare,  we don't need this, so reverting the code back.
> Revert "ROC-3089: Calculate response deadline based on calendar days"

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/ccj/CCDCountyCourtJudgment.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/ccj/CCDRepaymentPlan.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/ccj/CountyCourtJudgmentMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/ccj/RepaymentPlanMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/CountyCourtJudgmentAssert.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/RepaymentPlanAssert.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/ccj/CountyCourtJudgmentMapperTest.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/ccj/RepaymentPlanMapperTest.java
[ROC-3027](https://tools.hmcts.net/jira/browse/ROC-3027)
This PR change the type of Date objects to LocalDate for CCJ components as this is supported by CCD.
> ROC-3027: Change type from String to LocalDate

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/BaseIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/ClaimStore.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/AcceptOrRejectOfferTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GetClaimsByDefendantIdTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/IsDefendantLinkedTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/LinkDefendantToClaimTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/MakeOfferTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/RequestMoreTimeForResponseTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ResendStaffNotificationsTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveDefendantResponseTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/errors/EndpointErrorsTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/config/DbConfiguration.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/IntegrationTestSupportController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/SupportController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/ClaimRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/LegacyCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/TestingSupportRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/search/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/search/CaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/search/DBCaseRepository.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/MockSpringTest.java
and add to case repository
https://tools.hmcts.net/jira/browse/ROC-3024
> ROC-3097 Use external ID for defendant linking

- src/main/resources/citizen/templates/document/claimIssueReceipt.html
[ROC-3126](https://tools.hmcts.net/jira/browse/ROC-3126)
Add "issued on" date to claim receipt
> ROC-3126: Add "issued on" date to claim receipt

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/ClaimAssert.java
[ROC-3027](https://tools.hmcts.net/jira/browse/ROC-3027)
This PR adds missing field responseDeadline in CCD
> ROC-3027: Add missing response deadline field in CCD

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
[ROC-3027](https://tools.hmcts.net/jira/browse/ROC-3027)
This PR fixes the issue occurred during merge. Fix generates the correct JSON data.
> ROC-3027: Fix save claim to CCD 

- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java
ROC-3027
This PR fixes the merge issue
> ROC-3027: Fix merge issue

- build.gradle
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/BaseTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/Bootstrap.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/TestInstance.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/TestUser.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/aat/SaveClaimTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SaveClaimTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/smoke/RetrieveCaseTest.java
- src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/ROC-3152
Provide smoke tests that will be executed during CNP delivery pipeline.
```
[ ] Yes
[X] No
```
> ROC-3152: Delivery pipeline smoke tests

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CaseEvent.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/response/CCDResponse.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/response/ResponseMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/ResponseAssert.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/BaseSaveTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/ClaimStore.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/AcceptOrRejectOfferTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateClaimIssueReceiptTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateDefendantResponseCopyTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateDefendantResponseReceiptTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateSettlementAgreementCopyTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ResendStaffNotificationsTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimWithCoreCaseDataStoreTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/errors/EndpointErrorsTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/ClaimRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/DefendantResponseService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/search/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/search/CaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/search/DBCaseRepository.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/fixtures/SampleUserDetails.java
https://tools.hmcts.net/jira/browse/ROC-3026
> ROC-3026 Save defendant response in ccd

- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/IntegrationTestSupportController.java
This PR fixes the integration tests.
> ROC-3206:  Fix Integration tests

- src/test/java/uk/gov/hmcts/cmc/claimstore/processors/JsonMapperTest.java
This PR adds missing unit test for JsonMapper class.
> Add missing unit test

- build.gradle
> * Remove smoke from functional tests

- Jenkinsfile_parameterized
> Use master of Infrastructure library

- infrastructure/main.tf
A change was made in cnp which made these required vars
> Add webapp vars

- build.gradle
Don't check unit test code coverage
```
[ ] Yes
[x] No
```
> ROC-2832: exclude ccd-claim-migration from code coverage check

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculator.java
https://tools.hmcts.net/jira/browse/ROC-3200
Refactor code to make it simpler and improve code quality
```
[ ] Yes
[X] No
```
> ROC-3200 Fix code quality issue

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculator.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculatorTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimDataContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/DefendantPinLetterContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/InterestContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/countycourtjudgment/AmountContentProvider.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/InterestProviderTest.java
Functional tests fail after 4pm because the issuedOn date goes to the next day but the to date for interest is still today
While this case isn't really valid for CCJ,
1. It happens during testing and breaks the journey
2. It happens in the functional tests and breaks deployment
3. It is a valid case for the defendant journey and needs to be handled
@robertparkinson FYI
```
2018-02-28T21:54:03.077+0000 ERROR [http-nio-31478-exec-6] uk.gov.hmcts.cmc.claimstore.controllers.advices.ResourceExceptionHandler:41: StartDate cannot be
after endDate
at uk.gov.hmcts.cmc.domain.amount.TotalAmountCalculator.requireValidOrderOfDates(TotalAmountCalculator.java:105)
at uk.gov.hmcts.cmc.domain.amount.TotalAmountCalculator.daysBetween(TotalAmountCalculator.java:96)
at …
```
> Revert calculate interest using issedOn date

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculator.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculatorTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimDataContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/DefendantPinLetterContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/InterestContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/countycourtjudgment/AmountContentProvider.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/InterestProviderTest.java
Reverts hmcts/cmc-claim-store#226
Going to look at fixing the test case instead
> Revert "Revert calculate interest using issedOn date"

- Jenkinsfile_CNP
- infrastructure/main.tf
Updated Jenkinsfile_CNP. 
```
[x] Yes
[ ] No
```
> ROC-2832: add migration config to Jenkinsfile_CNP

- Jenkinsfile_CNP
Wrap strings in ''
```
[x] Yes
[ ] No
```
> ROC-2832: wrap strings in ''

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDClaim.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDTimeline.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDTimelineEvent.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/ClaimMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/TimelineEventMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/TimelineMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/Assertions.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/TimelineAssert.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/TimelineEventAssert.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/TimelineEventMapperTest.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/TimelineMapperTest.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/ClaimData.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Timeline.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/TimelineEvent.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/ClaimDataTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/TimelineEventTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/TimelineTest.java
- domain-model/src/test/resources/claim-application.json
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimData.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleTimeline.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleTimelineEvent.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SubmitClaimTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimDataContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/models/ClaimContent.java
- src/main/resources/citizen/templates/document/claimIssueReceipt.html
- src/test/java/uk/gov/hmcts/cmc/claimstore/processors/JsonMapperTest.java
- src/test/resources/claim-application.json
[ ROC-2213](https://tools.hmcts.net/jira/browse/ROC-2213)
This PR implements the timeline events for claimant to be stored in claim-store and CCD. 
>  ROC-2213 Enter claim timeline

- Jenkinsfile_CNP
> Disable CCD migration as VNET peering is missing

- Jenkinsfile_CNP
We have approval for the vnet peering, won't merge this till I've tested
the connectivity though
> Re-enable CCD migration

- Jenkinsfile_CNP
Update aat s2s config
```
[x] Yes
[ ] No
```
> ROC-2832: add s2s config

- Jenkinsfile_CNP
rename env var
```
[x] Yes
[ ] No
```
> ROC-2832: rename env var

- src/main/resources/staff/templates/document/sealedClaim.html
This PR adds the timeline events in sealed claim PDF.
> ROC-2213: Add timeline in sealed claim pdf

- Jenkinsfile_parameterized
> Remove slack notification from sandbox

- Jenkinsfile_CNP
- infrastructure/main.tf
Decision has been made that we will not be using CCD for go-live on
public beta
> Disable CCD everywhere

- .travis.yml
Codacy jar is failing to download on travis constantly, works on my machine, I think its a DNS issue...
```
[ ] Yes
[ ] No
```
> Remove codacy coverage as its failing the build

- .travis.yml
Add docker to travis? I think thats why travis stopped working on us
```
[ ] Yes
[ ] No
```
> Add docker for api tests on travis

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/countycourtjudgment/RepaymentPlanContentProvider.java
https://tools.hmcts.net/jira/browse/ROC-3258
corrected code as per sonar issue
```
[ ] Yes
[* ] No
```
> ROC-3258: Remove first payment amount from CCJ repayment plan

- src/main/resources/staff/templates/document/defendantPinLetter.html
Signed off again from Xerox after they used the right printer...
> Move address for envelope positioning

- infrastructure/main.tf
Requested by Martin and bulk print team
> Enable bulk print in production

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/DefendantTimeline.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Timeline.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/amount/AmountBreakDown.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/evidence/Evidence.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/evidence/EvidenceTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/ClaimDataTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/DefendantEvidenceTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/DefendantTimelineTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/TimelineTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SubmitClaimTest.java
Before we restricted to 20, we added javascript in the frontend but
didn't add validation there, BA has asked for this limit to be increased
across the board as it was arbitrary and users are trying to add more
https://tools.hmcts.net/jira/browse/ROC-3457
> ROC-3457 Fix timeline validation issue

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculator.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Claim.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculatorTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/InterestRatesController.java
[ROC-3455](https://tools.hmcts.net/jira/browse/ROC-3455)
This PR adds the endpoint to calculate interest for an claim. This will be used by the front-end.
`citizen-frontend` changes are in PR: https://github.com/hmcts/cmc-citizen-frontend/pull/498 
> ROC-3455: Fix for defendant journey broken for interest

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculator.java
This PR cleanup code against the potential null and removes code smell.
> ROC-3455: Cleanup code for potential null 

- Jenkinsfile
- build.gradle
My last PR broke them as it requires a new env var set, not a spring var so can't add it to aat.properties
Code stolen from send-letter-consumer, tested locally
> Fix functional and smoke tests

- infrastructure/aat.tfvars
- infrastructure/preview.tfvars
AAT is now going to point to tactical preprod
Can't merge until IDAM have done a release into preprod though
> Add config for tactical preprod

- Jenkinsfile_CNP
- infrastructure/output.tf
- src/aat/resources/environment.properties
- src/main/java/uk/gov/hmcts/cmc/claimstore/idam/IdamApi.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/idam/models/AuthenticateUserResponse.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/idam/models/Oauth2.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/UserService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/UserServiceTest.java
Fixed the smoke tests to use new idam api.
> Fix smoke tests with new idam api

- src/integrationTest/resources/environment.properties
- src/main/java/uk/gov/hmcts/cmc/claimstore/idam/IdamApi.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/idam/models/TokenExchangeResponse.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/UserService.java
This PR refactors the code done for fix and fixes breaking tests.
> Refactor code and fix tests

- src/integrationTest/resources/environment.properties
Add missing environment variable.
> Add missing env property

- src/main/resources/application.yml
This PR adds oauth client id fro idam in application yml
> Add oauth client id in application yml

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/idam/IdamTestService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/idam/IdamApi.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/idam/models/Oauth2.java
Also https://github.com/hmcts/cmc-integration-tests/pull/175
> Authenticate pin users with oauth2

- domain-model/src/test/resources/claim-application.json
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SamplePayment.java
- src/test/resources/claim-application.json
Functional tests have been sending bad data which was breaking the
payment report
> ROC-3570 Fix payment report

- infrastructure/main.tf
Relates to: https://tools.hmcts.net/jira/browse/RPE-422
Switch to new bulk print service that has producer and consumer bundled together. No API contract change.
```
[ ] Yes
[x] No
```
> Switch to new bulk print service

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/ROC-3550
Added an `afterCheckout` hook to the pipeline to update the demo branches with latest master changes.
> ROC-3550: Update demo branch on changes to master

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/LinkDefendantTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/RespondToClaimTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SettlementOfferTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/CommonOperations.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/BaseOfferTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GetClaimsByDefendantIdTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/IsDefendantLinkedTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/LinkDefendantToClaimTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/MakeOfferTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/RequestMoreTimeForResponseTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ResendStaffNotificationsTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveDefendantResponseTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/StaffEmailServiceWithNotificationDisabledTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/errors/EndpointErrorsTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/ClaimRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/DBCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/fixtures/SampleUser.java
https://tools.hmcts.net/jira/browse/ROC-3578
Remove v1 api
```
[ ] Yes
[x] No
```
> ROC-3578 Remove defendant link v1 api

- src/main/resources/citizen/templates/document/defendantResponseReceipt.html
https://tools.hmcts.net/jira/browse/ROC-3706
Add text '(as amended)' under the address section when defendant address details updated
```
[ ] Yes
[x ] No
```
> ROC-3706: Add amended flag when defendant address is updated

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDInterest.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/InterestMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/InterestAssert.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/InterestDateAssert.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/InterestMapperTest.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/ClaimData.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Interest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/ClaimDataDeprecableTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/InterestTest.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleInterest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/processors/JsonMapperTest.java
- src/test/resources/claim-application.json
https://tools.hmcts.net/jira/browse/ROC-3429
This is the first step to deliver this story. 
```
[ ] Yes
[X] No
```
> ROC-3429: Duplicate interestDate under interest

- web.config
It doesn't seem to get autocreated
```
[ ] Yes
[ ] No
```
> Ditch application folder

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/rpa/ClaimIssuedNotificationServiceTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rpa/ClaimIssuedNotificationService.java
> Don't send RPA json on legal

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/ClaimStore.java
https://tools.hmcts.net/jira/browse/ROC-3738
Fix Spring tests that started to fail past 4PM.
```
[ ] Yes
[X] No
```
> ROC-3738: Calculate the response deadline correctly for Spring tests

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/response/CaseReference.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/PrePaymentTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java
https://tools.hmcts.net/jira/browse/ROC-3730
Added endpoint stub
```POST /claims/$externalId/pre-payment```
```
[ ] Yes
[x] No
```
> ROC-3730: Add endpoint for pre-payment

- rpa-mapper/src/main/java/uk/gov/hmcts/cmc/rpa/mapper/SealedClaimJsonMapper.java
- rpa-mapper/src/test/java/uk/gov/hmcts/cmc/rpa/mapper/SealedClaimJsonMapperTest.java
- rpa-mapper/src/test/resources/sole_trader_rpa_case.json
https://tools.hmcts.net/jira/browse/ROC-3819
Adding prefix of 'Trading as' only in the case of sole trader consistent with PDFs we generate.
```
[ ] Yes
[X] No
```
> ROC-3819: Add 'trading as' prefix to business name in RPA JSON

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- dependency-check-suppressions.xml
- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/ROC-3940
Use azure key vault for secrets instead of hashi vault
```
[ ] Yes
[x] No
```
> ROC-3940 Use azure keyvault for secrets

- job-scheduler/src/main/java/uk/gov/hmcts/cmc/scheduler/config/QuartzConfiguration.java
- src/aat/resources/environment.properties
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/MockedDatabaseConfiguration.java
- src/integrationTest/resources/environment.properties
Mock the db on functional tests
```
[ ] Yes
[ ] No
```
> Mock database fully on functional tests

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/statementofmeans/Debt.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/statementofmeans/DebtTest.java
https://tools.hmcts.net/jira/browse/ROC-3658
As requested by Marc service should allow monthly debt payment to be 0.
```
[ ] Yes
[x] No
```
> ROC-3658: Allow monthly debt payment to be 0

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/ValidChildConstraintValidator.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/ValidEmploymentConstraintValidator.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/ValidExpenseConstraintValidator.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/ValidFullAdmissionConstraintValidator.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/ValidIncomeConstraintValidator.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/ValidResidenceConstraintValidator.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/constraints/ValidUnemploymentConstraintValidator.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/constraints/ValidChildConstraintValidatorTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/constraints/ValidEmploymentConstraintValidatorTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/constraints/ValidExpenseConstraintValidatorTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/constraints/ValidFullAdmissionConstraintValidatorTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/constraints/ValidIncomeConstraintValidatorTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/constraints/ValidResidenceConstraintValidatorTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/statementofmeans/ExpenseTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/statementofmeans/IncomeTest.java
https://tools.hmcts.net/jira/browse/ROC-3849
Refactoring, better error messages and nullable validators.
```
[ ] Yes
[x] No
```
> ROC-3849 Test improvements

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/statementofmeans/DependantMapper.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/response/Response.java
> ROC-3849: Remove @NotNull from 'moreTimeNeeded' and fix SoM save issue when no children

- infrastructure/main.tf
- infrastructure/variables.tf
Add tags to allow previews to be shutdown when PRs are close
```
[ ] Yes
[ ] No
```
> Add tags to infra

- rpa-mapper/src/main/java/uk/gov/hmcts/cmc/rpa/mapper/helper/RPAMapperHelper.java
- rpa-mapper/src/test/resources/claim/sole_trader_rpa_case.json
- rpa-mapper/src/test/resources/defence/sole_trader_rpa_case.json
https://tools.hmcts.net/jira/browse/ROC-4113
Replacing 'Trading as' to 'T/A' for sole trader for sealed claim and defence RPA JSON. 
```
[ ] Yes
[X] No
```
> ROC-4113: Replacing 'Trading as' with 'T/A' for sole trader

- infrastructure/demo.tfvars
> Disable DM on demo as its not working for legal

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java
Actually tested it this time ^.^
Needed one more change my bad
> Revert change that broke perf tests (again)

- src/main/resources/citizen/templates/document/claimIssueReceipt.html
- src/main/resources/staff/templates/document/sealedClaim.html
https://tools.hmcts.net/jira/browse/ROC-4184
Add word wrap to large unbroken strings to fix text wrapping issues in PDF generation
```
[ ] Yes
[x ] No
```
> Add break-word word wrap on claim issue template table data

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/CaseMetadata.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/CaseMetadataControllerTest.java
https://tools.hmcts.net/jira/browse/ROC-4253
Update case metadata to include the payment reference number
```
[ ] Yes
[x] No
```
> ROC-4253: Update case metadata to include the payment reference number

- rpa-mapper/src/main/java/uk/gov/hmcts/cmc/rpa/mapper/RequestForJudgementJsonMapper.java
- rpa-mapper/src/test/resources/judgement/rpa_request_for_judgement_by_set_date.json
- rpa-mapper/src/test/resources/judgement/rpa_request_for_judgement_fortnightly.json
- rpa-mapper/src/test/resources/judgement/rpa_request_for_judgement_immediately.json
- rpa-mapper/src/test/resources/judgement/rpa_request_for_judgement_immediately_nothing_paid.json
- rpa-mapper/src/test/resources/judgement/rpa_request_for_judgement_monthly.json
- rpa-mapper/src/test/resources/judgement/rpa_request_for_judgement_weekly.json
https://tools.hmcts.net/jira/browse/ROC-4259
Bug fix - Incorrect value for field amountWithInterest on RPA judgement JSON
```
[ ] Yes
[X] No
```
> ROC-4259: Live bug fixing amountWithInterest for judgement JSON

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java
- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/mappers/ClaimMapper.java
- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/mappers/JsonMapper.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Claim.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/ClaimantResponse.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/ResponseAcceptation.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/ResponseRejection.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/ResponseAcceptationTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/ResponseRejectionTest.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaim.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimantResponse.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ClaimantResponseTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/CommonOperations.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimantResponseTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsightsEvent.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimantResponseController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/exceptions/ClaimantLinkException.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/exceptions/ClaimantResponseAlreadySubmittedException.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/ClaimRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/DBCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/mapping/ClaimMapper.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rules/ClaimantResponseRule.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseService.java
- src/main/resources/db/migration/claimstore/V2018_08_14_1445__Add_claimant_response_columns.sql
- src/test/java/uk/gov/hmcts/cmc/claimstore/rules/ClaimantResponseRuleTest.java
https://tools.hmcts.net/jira/browse/ROC-4207
Save claimant response - future PRs for validation and emails
```
[ ] Yes
[ x ] No
```
> ROC-4207 Claimant response

- infrastructure/aat.tfvars
https://tools.hmcts.net/jira/browse/ROC-4254
```
[ ] Yes
[ ] No
```
> ROC-4254 Switch back to TIDAM

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/solicitor/SolicitorPdfTest.java
https://tools.hmcts.net/jira/browse/ROC-4067
Refactoring of moving base test for functional test failed solicitor test on master build - `no runnable test’. Fixing by adding test in solicitorPdf test
```
[ ] Yes
[X] No
```
> ROC-4067: Fixing sols functional test

- Jenkinsfile_CNP
Changes to be merged manually today
> Disable auto demo merge

- infrastructure/aat.tfvars
> Point to SIDAM

- infrastructure/aat.tfvars
Reverts hmcts/cmc-claim-store#455
> [DO NOT MERGE] Back to TIDAM

- src/main/resources/citizen/templates/document/defendantResponseReceipt.html
https://tools.hmcts.net/jira/browse/ROC-4319
> ROC-4319 - Replace defence with response

- infrastructure/main.tf
Required after dependency upgrade (breaking change in patch version -.-)
https://github.com/pgjdbc/pgjdbc/blob/master/CHANGELOG.md
> Add new sslmode property

- src/kubernetes/deployment.template.yaml
Lower the k8s CPU request amount to allow denser scheduling of pods
```
[ ] Yes
[x] No
```
> lower k8s CPU request

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CaseEvent.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/response/CCDPartAdmissionResponse.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/response/CCDResponse.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/response/FullAdmissionResponseMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/response/PartAdmissionResponseMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/response/ResponseMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/Assertions.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/response/PartAdmissionResponseAssert.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/response/FullAdmissionResponseMapperTest.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/response/PartAdmissionResponseMapperTest.java
- infrastructure/main.tf
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/OffersService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
https://tools.hmcts.net/jira/browse/ROC-4010
Implement missing feature like part admission, ccd and settlement. and Enable ccd on demo
```
[ ] Yes
[ ] No
```
> ROC-4010 implement missing features in ccd

- src/main/resources/citizen/templates/document/defendantResponseReceipt.html
https://tools.hmcts.net/jira/browse/ROC-4397
Fixing statement around payment declaration within Def response pdf
```
[ ] Yes
[X] No
```
> ROC 4397: Fixing statement around payment declaration 

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/ResponseRejection.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimantResponse.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ClaimantResponseTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimantResponseTest.java
[ROC-4413](https://tools.hmcts.net/jira/browse/ROC-4413)
This PR removes `reason` from `ResponseRejection` and changes type of `freeMediation` to `Boolean`
> ROC-4413: Remove reason and change freeMediation to Boolean

- build.gradle
- dependency-check-suppressions.xml
Suppress CVE-2016-7048 causing PR failure on pipeline. Also check PR - https://github.com/hmcts/ccd-definition-store-api/pull/185/ how CCD fixed this issue at their side.
```
[ ] Yes
[X] No
```
> Suppress CVE-2016-7048

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/FormaliseResponseAcceptanceService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/FormaliseResponseAcceptanceServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
Adding test case to bump up code coverage over 80%. Will add more test if still under par. 
```
[ ] Yes
[X] No
```
> Fixing sonar low code coverage issues

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/RepaymentPlan.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/statementofmeans/CourtOrder.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/RepaymentPlanTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/statementofmeans/CourtOrderTest.java
[ROC-4436](https://tools.hmcts.net/jira/browse/ROC-4436)
This PR changes the validation for amount in CourtOrder and instalment amount for RepaymentPlan.
> ROC-4436: Change validation for amount and instalment amount

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/DefendantResponseStaffNotificationService.java
- src/main/resources/staff/templates/email/defendantAdmission/body.txt
- src/main/resources/staff/templates/email/defendantAdmission/subject.txt
Fix the email template for part admit already paid what defendant states he owes.
> ROC-4328: Part admit already paid email template

- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/CaseMetadataController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/ClaimRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/DBCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/CaseMetadataControllerTest.java
ROC-4631
Added endpoint to find claims with a given payment reference, to help the live support team resolve tickets around successful payments without claim reference notifications.
```
[ ] Yes
[x] No
```
> ROC-4631 Add support endpoint to find claims by payment reference

- src/kubernetes/deployment.template.yaml
Request from Tim Webster to lower CPU resources a bit from 500m to 200m
```
[ ] Yes
[X] No
```
> Adjust CPU resources and cron frequency on AKS

- infrastructure/aat.tfvars
- infrastructure/prod.tfvars
Planned and approved SIDAM production testing for CMC
> sidam dry-run

- build.gradle
- codecov.yml
All master builds failing at sonar - 78.9% .
```
[ ] Yes
[ X ] No
```
> push coverage to 80%

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/CCJStaffNotificationServiceTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/CCJStaffNotificationService.java
- src/main/resources/staff/templates/email/redeterminationRequest/body.txt
Jira Link:
https://tools.hmcts.net/jira/browse/ROC-4728
> ROC-4728 Add reason for redetermination in staff email

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/ResponseAcceptation.java
https://tools.hmcts.net/jira/browse/ROC-4790
removed @NotNull check for formaliseOption in claimant responseAcceptation that was crashing when defendant states paid full defence
```
[ ] Yes
[x] No
```
> ROC-4790 States paid claimant response can't get to confirmation page

- src/main/resources/db/migration/claimstore/V2018_11_21_1635__Remove_ccj_issued_at_column.sql
https://tools.hmcts.net/jira/browse/ROC-4370
Removing CCJ issued at after merge of ROC-4370, we're required to remove unused field county_court_judgment_issued_at from DB.
```
[ ] Yes
[X] No
```
> ROC: 4370 - Removing CCJ issued at

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/claimantresponse/ResponseAcceptation.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimantResponse.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimantResponseTest.java
https://tools.hmcts.net/jira/browse/ROC-4790
added test for response acceptation with formaliseOption null
```
[ ] Yes
[x] No
```
> ROC-4790 added tests  for response acceptation with formaliseOption null

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-4805
When rejecting a partial admission with no mediation, store the directions questionnaire deadline
```
[ ] Yes
[x] No
```
> ROC-4805 rejected part admit directions questionnaire deadline

- dependency-check-suppressions.xml
suppress-dependency-check-for-CVE-2018-8088
```
[ ] No
```
> suppress-dependency-check-for-CVE-2018-8088

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/defendant/CCDDefendant.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/claimantresponse/ClaimantResponseMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/defendant/DefendantMapper.java
This PR adds the missing mappings for claimant response.
> Add missing mappings for claimant response

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/ClaimMapper.java
[ROC-5044](https://tools.hmcts.net/jira/browse/ROC-5044)
This PR implements the change to display total amount on CCD UI. 
> ROC-5044: Show totalAmount on CCD UI

- build.gradle
excluding CCD classes for sonar qube quality gate percentage
```
[ ] Yes
[x] No
```
> Sonar qube exclusions

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
Update helm chart to use rpe feature-toggle chart
```
[ ] Yes
[ ] No
```
> update feature-toggle-api chart

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
- charts/cmc-claim-store/values.template.yaml
Fix our AKS chart failiures. Tested in citizen-frontend.
```
[ ] Yes
[ x ] No
```
> Fix feature toggle api helm chart

- .travis.yml
https://tools.hmcts.net/jira/browse/ROC-5108
Fix and using docker script instead of docker-less.
```
[ ] Yes
[X] No
```
> ROC-5108: Fix for swagger not getting published

- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleResponse.java
- rpa-mapper/src/main/java/uk/gov/hmcts/cmc/rpa/mapper/DefenceResponseJsonMapper.java
- rpa-mapper/src/test/java/uk/gov/hmcts/cmc/rpa/mapper/AdmissionResponseJsonMapperTest.java
- rpa-mapper/src/test/resources/admissions/individual_part_admission_states_paid.json
- rpa-mapper/src/test/resources/admissions/sole_trader_part_admission_states_paid.json
- src/test/java/uk/gov/hmcts/cmc/claimstore/rules/ClaimantResponseRuleTest.java
https://tools.hmcts.net/jira/browse/ROC-5200
LIVE BUG please prioritise - RPA for part admit - states paid is failing causing FE builds to stall. 
```
[ ] Yes
[X] No
```
> ROC-5200 : LIVE BUG - RPA partadmits, states paid fix

- Dockerfile
updating to the new java image to reduce AKS resources in PR's
> new java image

- charts/cmc-claim-store/values.template.yaml
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java
https://tools.hmcts.net/jira/browse/ROC-5251
Just for testing an issue with PRs that behave if admissions is off. Checked feature-toggle-imported, roles in cmc db, everything looks fine. One thing thats odd - the claim entry populates features column with a string value 'null'.
Will use this PR to run some tests and cleanup after.
https://tools.hmcts.net/jira/browse/ROC-5251
```
[ ] Yes
[ x ] No
```
> ROC-5251: fix feature-toggle service port

- Jenkinsfile_nightly
- security.sh
> set up cmc claim store security scan

- Jenkinsfile_CNP
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/CaseMetadata.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Claim.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaim.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/DownloadRepresentedClaimCopyWithDocumentManagementTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimWithDocumentManagementTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimIssueReceiptService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/CountyCourtJudgmentPdfService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/DefendantResponseReceiptService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/PdfService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/SealedClaimPdfService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/SettlementAgreementCopyService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/DocumentGenerator.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rpa/ClaimIssuedNotificationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementBackedDocumentsService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/ClaimIssuedStaffNotificationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/DocumentNameUtils.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/CaseMetadataControllerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/DocumentGeneratorTest.java
https://tools.hmcts.net/jira/browse/ROC-3960
store the claim issue receipt \ claimant copy in DM 
```
[X ] No
```
> ROC-3960-store-claimant-copy-claim-form

- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java
Filter cases for the user id.
[ROC-5324](https://tools.hmcts.net/jira/browse/ROC-5324)
> ROC-5324: Resolve search by defendantId

- charts/cmc-claim-store/values.template.yaml
Reduce CPU requests for Postgres containers to avoid resource hogging
```
[ ] Yes
[x] No
```
> reduce postgres cpu request

- charts/cmc-claim-store/values.template.yaml
https://tools.hmcts.net/jira/browse/ROC-5240
feature toggle for directions questionnaire FF4J
```
[ ] Yes
[x] No
```
> add feature toggle for DQs FF4J

- Jenkinsfile_CNP
RDM-4318
Decouple master merge to initiate demo deployment
> RDM-4318 Decouple master merge to initiate demo deployment

- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/UserService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
[ROC-5406](https://tools.hmcts.net/jira/browse/ROC-5406)
This PR improves instrumentation for ccd case creation operation.
> ROC-5406: Improve instrumentation for ccd case creation

- build.gradle
CVE-2019-9658 fix
```
[ ] Yes
[X] No
```
> CVE-2019-9658 fix

- charts/cmc-claim-store/values.template.yaml
- src/main/resources/bootstrap.yml
https://tools.hmcts.net/jira/browse/ROC-5368
Mapping all secrets - new env not picking them up.
```
[ ] Yes
[ x ] No
```
> Add db-passwords to secrets and aliases for new aat aks env

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/CaseMetadata.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/CaseMetadataControllerTest.java
https://tools.hmcts.net/jira/browse/ROC-5430
Added claimant response date to the metadata controller responses
```
[ ] Yes
[x] No
```
> ROC-5430 Add claimant responded at date to metadata results

- src/main/resources/citizen/templates/document/claimIssueReceipt.html
- src/main/resources/citizen/templates/document/defendantResponseReceipt.html
- src/main/resources/staff/templates/document/sealedClaim.html
https://tools.hmcts.net/jira/browse/ROC-5358
Changed the words in the PDF templates
```
[ ] Yes
[x] No
```
> ROC-5358 Replace "submitted" with "received" in claim, sealed-claim and response PDFs

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
- charts/cmc-claim-store/values.template.yaml
Update citizen-frontend Helm chart version (new feature-toggle-importer changes)
```
[ ] Yes
[x] No
```
> Bump citizen-frontend helm chart version

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/ClaimAssert.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculator.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Claim.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/utils/MonetaryConversions.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculatorTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/utils/MonetaryConversionsTest.java
https://tools.hmcts.net/jira/browse/ROC-5357
Adding the interest amount till issued date to CCD
```
[ ] Yes
[x] No
```
> ROC-5357 Map interest till date of issue to CCD

- infrastructure/demo.tfvars
- infrastructure/saat.tfvars
- infrastructure/sprod.tfvars
Update demo to SIDAM to bring in-line with AAT and Production.
```
[ ] Yes
[ x ] No
```
> Point to SIDAM (demo/saat/sprod)

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/DummyBulkPrintRequestTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/DummyBulkPrintService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/PrintService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/DummyBulkPrintServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-5583
Add dummy implementation for send letter for local testing
```
[ ] Yes
[ ] No
```
> ROC-5583: Add dummy implementation for send letter

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDNotKnown.java
This PR cleans up the redundant amount type in CCD domain
> Cleanup redundant amount type in CCD domain

- ccd-claim-migration/build.gradle
- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/repositories/ClaimRepository.java
- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/services/ClaimMigrator.java
- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/services/MigrationHandler.java
- ccd-claim-migration/src/main/resources/application.yml
[ROC-5588](https://tools.hmcts.net/jira/browse/ROC-5588)
This PR customises CCD migration so that we can run a subset of claims with given reference numbers.
> ROC-5588: Customise ccd migration to run a subset

- build.gradle
Tomcat used in spring boot has a remote code execution vulnerability (CVE-2019-0232). Pinning latest version to fix that.
```
[ ] Yes
[x] No
```
> CVE-2019-0232: Upgrade spring boot version and pin tomcat version

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementBackedDocumentsService.java
https://tools.hmcts.net/jira/browse/ROC-5605
changed to save pdf file size in db
```
[x ] No
```
> ROC-5605 pdf file size not being saved

- infrastructure/main.tf
Broken pipeline - needs updating.
```
[ ] Yes
[x] No
```
> Remove explicit Azure Provider version

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/idam/IdamTestService.java
Issue identified to LDAP. Delay is unnecessary so removing.
```
[ ] Yes
[x] No
```
> Remove unnecessary IDAM delay from functional tests

- src/main/java/uk/gov/hmcts/cmc/claimstore/config/CCDStoreConfiguration.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/config/NotificationsConfiguration.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/ccj/CCJStaffNotificationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/ClaimCreationEventsStatusService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/DocumentOrchestrationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/PinOrchestrationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/PostClaimOrchestrationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/offer/AgreementCountersignedStaffNotificationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/operations/ClaimantOperationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/operations/NotifyStaffOperationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/operations/RpaOperationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/operations/UploadOperationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/response/DefendantResponseStaffNotificationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/response/MoreTimeRequestedStaffNotificationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/support/CCDTestingSupportRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rpa/ClaimIssuedNotificationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rpa/DefenceResponseNotificationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rpa/MoreTimeRequestedNotificationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rpa/PaidInFullNotificationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rpa/RequestForJudgementNotificationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rpa/RpaNotificationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ReferenceNumberService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CCDCreateCaseService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/ClaimIssuedStaffNotificationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/ClaimIssuedStaffNotificationService.java
Add specific value check for feature toggles
```
[ ] Yes
[ ] No
```
> Add specific value for feature toggles

- Jenkinsfile_CNP
Disable as part of CCD 1.2.3 release - so Demo is in working state.
```
[ ] Yes
[x] No
```
> Disable demo git copy

- charts/cmc-claim-store/values.preview.template.yaml
Updated frontend chart and broke this! Added missing env vars. Tested manually.
```
[ ] Yes
[x] No
```
> Fix bad chart update :(

- src/main/resources/db/migration/claimstore/V2019_05_15_1500__set_claim_submission_operation_indicators_for_existing_claims.sql
> Set operation idicators for existing claims

- src/main/resources/db/migration/claimstore/V2019_05_15_1500__remove_defendantPinLetter_from_operation_indicators.sql
> Cleanup flyway state for pipelines

- infrastructure/main.tf
- src/main/resources/db/migration/claimstore/V2019_05_15_1500__set_claim_submission_operation_indicators_for_existing_claims.sql
This PR pushes the old script to recover flyway state to be repaired without manual intervention of database.
```
[ ] Yes
[ ] No
```
> Push the old patch to recover flyway state

- email-client/src/main/java/uk/gov/hmcts/cmc/email/EmailService.java
- email-client/src/test/java/uk/gov/hmcts/cmc/email/EmailServiceTest.java
- infrastructure/main.tf
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/ClaimOperation.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/ClaimCreationEventsStatusService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/DocumentOrchestrationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/GeneratedDocuments.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/PinOrchestrationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/PostClaimOrchestrationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/operations/ClaimantOperationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/operations/UploadOperationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementBackedDocumentsService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/ClaimIssuedNotificationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/NotificationService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/PinOrchestrationServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/PostClaimOrchestrationHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/offer/CountersignSettlementAgreementActionsHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/operations/UploadOperationServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/CCJNotificationServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/ClaimIssuedNotificationServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/DefendantResponseNotificationServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/NotificationServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/NotificationToDefendantServiceTest.java
Resolve Async handling on failures
```
[ ] Yes
[ ] No
```
> Resolve Async handling on failures

- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/ClaimCreationEventsStatusService.java
https://tools.hmcts.net/jira/browse/ROC-5467
Fix for updating the claim submission indicator
> Fix for updating the claim submission indicator

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimWithDocumentManagementTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/CCDEventProducer.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/ccd/CCDCaseHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/ccd/CCDLinkLetterHolderEvent.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/DocumentOrchestrationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/SupportControllerTest.java
Add link letter holder in ccd async handler
```
[ ] Yes
[ ] No
```
> Add link letter holder in ccd async handler

- build.gradle
> Fix for CVE-2019-12086

- Jenkinsfile_parameterized
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDDocument.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/ClaimDocumentMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/ClaimDocumentMapperTest.java
https://tools.hmcts.net/jira/browse/ROC-5732
Add the document binary Url and document name in ccd document
```
[X ] No
```
> ROC-5732: Add the document binary Url and document name in ccd document

- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/services/MigrationHandler.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/ClaimState.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/ClaimStore.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/support/GetMetadataTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/CaseMetadataController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/DBCaseRepository.java
- src/main/resources/db/migration/claimstore/V2019_05_28_1500__rename_created_state_to_create.sql
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/CaseMetadataControllerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
This PR renames the Claim state to `create` to match with what we have in CCD definitions.
> Rename the Claim state to `create`

- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/ccd/services/MigrateCoreCaseDataService.java
- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/ccd/services/UpdateCCDCaseService.java
- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/services/MigrationHandler.java
Update Claim state check in migration
```
[ ] Yes
[ ] No
```
> Update Claim state check in migration

- infrastructure/aat.tfvars
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/solicitor/SolicitorPdfTest.java
> Enable async operation for aat

- build.gradle
Disable functional tests temporarily 
```
[ ] Yes
[ ] No
```
> Disable functional tests

- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java
This PR removes the un-necessary filter check
> Remove invalid filter check

- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java
Fix filtering for dashboard
```
[ ] Yes
[ ] No
```
> Fix filtering for dashboard

- charts/cmc-claim-store/values.preview.template.yaml
Already using 1.2.5 in prod so should bump for PRs too.
```
[ ] Yes
[x] No
```
> Bump CCD definitions in PRs to 1.2.5

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDClaimDocumentType.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CaseEvent.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/DrawOrderCallbackHandlerTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/DrawOrderCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/GenerateOrderCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/MoreTimeRequestedCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/CallbackHandlerFactoryTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/DrawOrderCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-5489
On draw order, we copy the draft order doc in case documents
```
[ ] Yes
[x] No
```
> ROC-5489 Draw order and copy doc in case documents

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDApplicant.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/defendant/CCDRespondent.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/legaladvisor/CCDHearingCourtType.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/legaladvisor/CCDResponseSubjectType.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/util/SampleData.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateOrderCallbackHandlerTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/courtfinder/models/Address.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/GenerateOrderCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBody.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBodyMapper.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/HearingCourt.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/courtfinder/models/AddressTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/GenerateOrderCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBodyMapperTest.java
- src/test/resources/doc-assembly-template.json
**xefore creating a pull request make sure that:**
https://tools.hmcts.net/jira/browse/ROC-5518
Populate the legal order with court name / address  depending on DQ answers.
NOTE - only latest commit has to be reviewed, the rest has been approved in another pr :)
```
[ ] Yes
[x] No
```
> ROC-5518 Populate legal order court name and address

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/InterestMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/InterestMapperTest.java
Handle Null interest type in claim interest
```
[ ] Yes
[ ] No
```
> Handle Null interest type in claim interest

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/statementofmeans/CourtOrder.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/statementofmeans/Expense.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/statementofmeans/PriorityDebt.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/statementofmeans/ExpenseTest.java
[ROC-5801](https://tools.hmcts.net/jira/browse/ROC-5801)
This pull request fixes the inconsistent validation. 
> ROC-5801: Fix inconsistent validation

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-5213
CCD 1.2.8 released to PROD
```
[ ] Yes
[x] No
```
> CCD release 1.2.8

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.preview.template.yaml
My bad...I bumped citizen-frontend chart minor but included breaking change! This PR fixes to use new value format for IDAM PR chart.
```
[ ] Yes
[x] No
```
> Update IDAM PR chart yaml for frontend deployment

- Dockerfile
RPE re-organised the images in hmcts public ACR. 
```
[ ] Yes
[x] No
```
> New java base image

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDReviewOrder.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/ReviewOrderMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/Assertions.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/ReviewOrderAssert.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/ReviewOrderMapperTest.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/ReviewOrder.java
[ROC-5992](https://tools.hmcts.net/jira/browse/ROC-5992)
This PR adds the new domain model for review order.
> ROC-5992: Add domain model for review order

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-5256
CCD release 1.2.12:
- definition changes only
```
[ ] Yes
[x] No
```
> CCD 1.2.12 Release

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.preview.template.yaml
- charts/cmc-claim-store/values.yaml
- docker-compose.yml
RPE driven requirement to use hmctspublic ACR repo.
```
[ ] Yes
[x] No
```
> Update to use hmctspublic

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/directionsquestionnaire/PilotCourt.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/directionsquestionnaire/PilotCourtTest.java
[ROC-6050](https://tools.hmcts.net/jira/browse/ROC-6050)
This PR updates the logic for pilot courts
> ROC-6050: Update logic for calculating pilot court

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDApplicant.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/legaladvisor/CCDHearingCourtType.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/legaladvisor/CCDOrderGenerationData.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/util/SampleData.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/DrawOrderCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GenerateOrderCallbackHandlerTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/DrawOrderCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/GenerateOrderCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBody.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBodyMapper.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/DirectionsQuestionnaireUtils.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/processors/JsonMapperTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/DrawOrderCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/GenerateOrderCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBodyMapperTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/utils/DirectionsQuestionnaireUtilsTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/utils/ResourceLoader.java
- src/test/resources/core-case-data/submit-response.success-with-dq.json
- src/test/resources/doc-assembly-template.json
https://tools.hmcts.net/jira/browse/ROC-5841
Mapping the hearing court details from DQ to the LA UI. Also fixing a bug in which case details were lost after drawing the order 😬 
```
[ ] Yes
[x] No
```
> ROC-5841 Map DQ hearing court to LA UI

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/idam/IdamTestService.java
Introducing a delay to overcome replication lag issues with IDAM (from advice by Kremena).
```
[ ] Yes
[x] No
```
> Delay between user creation and auth (recommended by idam support)

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-5570
CCD 1.2.21 release
```
[ ] Yes
[x] No
```
> CCD 1.2.21 release

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CaseEvent.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/DirectionsQuestionnaireUtils.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/utils/DirectionsQuestionnaireUtilsTest.java
https://tools.hmcts.net/jira/browse/ROC-6017
Triggering waiting for transfer event for online dq, no mediation, no pilot court
```
[ ] Yes
[x] No
```
> ROC-6017 Trigger Ready for transfer event for online dq

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/ClaimDocumentMapper.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/AcceptOrRejectOfferTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimantResponseTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveCountyCourtJudgementTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CountyCourtJudgmentController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/AlwaysGenerateDocumentsService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementBackedDocumentsService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/processors/JsonMapperTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementBackedDocumentsServiceTest.java
> Clean up code

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/DirectionsQuestionnaireUtils.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-6048
We now calculate the directions questionnaire deadline date for claimant response 
- only if the claim is not online dq
- both for full defence and part admission
```
[ ] Yes
[ ] No
```
> ROC-6848 Directions questionnaire date for offline dq

- Jenkinsfile_CNP
This PR disables auto merge to demo
> Disable auto merge to demo

- Jenkinsfile_CNP
enable auto merge to demo
```
[ ] Yes
[ x] No
```
> enable auto merge to demo

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
Bump ccd chart version
```
[ ] Yes
[ x] No
```
> Bump ccd chart version

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/Bootstrap.java
> Improve smoke test fix

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/ROC-4263
This is to be merged to master today for the Dry run of the testing Migration steps on old DEMO
```
[ ] Yes
[x ] No
```
> disable pushing to demo

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/BaseSubmitClaimTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/CountyCourtJudgementTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/RespondToClaimTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/SubmitClaimTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveCountyCourtJudgementTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveDefendantResponseTest.java
[ROC-6049](url)
This PR moves the negative scenarios from functional tests to integrations/mock layer.
> ROC-6049: Move negative scenarios in functional tests to integration

- charts/cmc-claim-store/values.preview.template.yaml
CCD 1.2.24 release (also bumped mediation from 10% to 100% - not really valid in PR env, we can control on/off with toggle)
```
[ ] Yes
[x] No
```
> CCD 1.2.24 release

- build.gradle
- dependency-check-suppressions.xml
- domain-model/build.gradle
> Fix CVE errors

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/DirectionOrderMapper.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/DrawOrderCallbackHandler.java
ROC-6307: Resolve optional fields and document name
```
[ ] Yes
[ ] No
```
> ROC-6307: Resolve optional fields and document name

- lib/AI-Agent.xml
Simplify AppInsights settings to match conventions with draft-store
```
[ ] Yes
[ x] No
```
> simplify ai-agent.xml

- build.gradle
- config/checkstyle/checkstyle.xml
This PR fixes the  CVE-2019-10086.
> Fix CVE-2019-10086

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBodyMapper.java
[ROC-6409](https://tools.hmcts.net/jira/browse/ROC-6409)
This PR fixes the `NullPointerException` on callback when LA triggers `Action review comments`
> ROC-6409: Fix callback error

- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/DirectionsQuestionnaireUtils.java
[ROC-6417](https://tools.hmcts.net/jira/browse/ROC-6417)
Fix illegal state error when claim above 300
> ROC-6417: Fix illegal state error when claim above 300

- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/directionsquestionnaire/HearingContentProvider.java
- src/main/resources/citizen/templates/document/claimantDirectionsQuestionnaire.html
- src/main/resources/citizen/templates/document/defendantResponseReceipt.html
https://tools.hmcts.net/jira/browse/ROC-6400
DQ pdf changes
> ROC-6400: Conditional pdf copy

- src/main/java/uk/gov/hmcts/cmc/claimstore/config/properties/notifications/EmailTemplates.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claimantresponse/ClaimantResponseActionsHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/NotificationToDefendantService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/claimantresponse/ClaimantResponseActionsHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/NotificationToDefendantServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-6418
Notify defendant for Claimant intention to proceed for paper dq
Email template is captured from https://tools.hmcts.net/jira/browse/ROC-6422
```
[ ] Yes
[ ] No
```
> ROC-6418:Notify defendant for Claimant intention to proceed for paper dq

- src/main/java/uk/gov/hmcts/cmc/claimstore/config/properties/notifications/EmailTemplates.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claimantresponse/ClaimantResponseActionsHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/NotificationToDefendantService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/DirectionsQuestionnaireUtils.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/claimantresponse/ClaimantResponseActionsHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/NotificationToDefendantServiceTest.java
Notify defendant for intention to proceed for online dq
```
[ ] Yes
[ ] No
```
> Notify defendant for intention to proceed for online dq

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDChannelType.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/ClaimAssert.java
- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/mappers/ClaimMapper.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/ChannelType.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Claim.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaim.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/mapping/ClaimMapper.java
[ROC-6128](https://tools.hmcts.net/jira/browse/ROC-6128)
Add channel to identify the source of a case.
Definition changes in this PR: https://github.com/hmcts/cmc-ccd-domain/pull/82
> ROC-6128: Add channel of case

- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/DirectionsQuestionnaireUtils.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/utils/DirectionsQuestionnaireUtilsTest.java
Handle null check for Claim features
```
[ ] Yes
[ ] No
```
> Handle null check for Claim features

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Payment.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/PaymentTest.java
https://tools.hmcts.net/jira/browse/ROC-6116
Payment nextUrl will be populated as part of IOC but should not yet constrained to `@NotBlank` for backward compatibility 
```
[ ] Yes
[x] No
```
> ROC-6116 Payment nextUrl should not be validated

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsights.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsightsExceptionLogger.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ExceptionForClient.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/appinsights/AppInsightsTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-6502
Add exception telemetry in app insights when exceptions are caught by the `ResourceExceptionHandler`
> ROC-6502 Add exception telemetry to requests

- rpa-mapper/src/main/java/uk/gov/hmcts/cmc/rpa/mapper/DefenceResponseJsonMapper.java
https://tools.hmcts.net/jira/browse/ROC-6542
Protect RPA generation from NPE when no features are listed on the claim
> ROC-6542 NPE protection on defence RPA generation

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/MediationRow.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleAmountBreakdown.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimData.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/MediationCSVGenerator.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/MediationCSVGeneratorTest.java
https://tools.hmcts.net/jira/browse/ROC-6444
Add Pilot Column to CSV file based on if its Pilot eligible.
> ROC-6444-Milo-Csv-Add-Pilot-Column

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-5962
Release definition 1.3.3
```
[ ] Yes
[ ] No
```
> Release definition 1.3.3

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CaseEvent.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/PaymentMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/ClaimAssert.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/PaymentMapperTest.java
- ccd-sample-data/src/main/java/uk/gov/hmcts/cmc/ccd/sample/data/SampleData.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Payment.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/PaymentStatus.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/ioc/CreatePaymentResponse.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SamplePayment.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/DBCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimControllerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
- src/test/resources/claim-application.json
https://tools.hmcts.net/jira/browse/ROC-6119
Adding endpoint in claimstore to resume a payment 
```
[ ] Yes
[x] No
```
> ROC-6119 Add resume payment for citizen endpoint

- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDElasticSearchRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/elastic/Query.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/repositories/elastic/QueryTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/repositories/elastic/SampleQueryConstants.java
https://tools.hmcts.net/jira/browse/ROC-6584
Remove the defaulting page size and increase it to 1000 for now.
> ROC-6584-Page Size setting for Elastic Search.

- infrastructure/main.tf
- infrastructure/variables.tf
So that prod and demo won't healthcheck on those clients.
```
[ ] Yes
[ ] No
```
> Disable fees and pay urls in tf files

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/BaseSaveTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/InitiatePaymentTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ResumePaymentTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/InitiatePaymentCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/ResumePaymentCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/legaladvisor/DrawOrderCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/legaladvisor/GenerateOrderCallbackHandlerTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/DBCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CallbackHandlerFactory.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/Role.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/AppInsightsCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/CallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/MoreTimeRequestedCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/PaymentsService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/DrawOrderCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/GenerateOrderCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legalrep/CreateLegalRepClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimControllerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/CallbackHandlerFactoryTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/InitiatePaymentCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/PaymentsServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legalrep/CreateLegalRepClaimCallbackHandlerTest.java
- src/test/resources/core-case-data/submit-response.success.json
https://tools.hmcts.net/jira/browse/ROC-6118
Adding callback to resume a citizen payment
```
[ ] Yes
[x] No
```
> ROC-6118 Add resume payment callback

- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/RoboticsSupportController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportController.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/RoboticsSupportControllerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportControllerTest.java
https://tools.hmcts.net/jira/browse/ROC-6619
Add support endpoints to resend RPA notifications for batches of claims
> ROC-6619 RPA support endpoints

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-6042
Using definition 1.4.2 for aks
```
[ ] Yes
[ ] No
```
> Using definition 1.4.2 for aks

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/PaymentMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/PaymentMapperTest.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/PaymentStatus.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/PaymentStatusTest.java
https://tools.hmcts.net/jira/browse/ROC-6630
There might be some payment statuses which are not correctly mapped in the enum, and this is creating problems in prob. Reverting to string while we get all of the possible values from devops.
```
[ ] Yes
[x] No
```
> ROC-6630 Map null payment status

- build.gradle
Cleans up gradle file after cve fix
> Clean up gradle file after cve fix

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/PaymentsService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/PaymentsServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-6116
Claimant has to pay just for the fee, not the claim amount.l
```
[ ] Yes
[x] No
```
> ROC-6116 Send payment amount for just the fee

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
https://tools.hmcts.net/jira/browse/ROC-5274
make use of chart-ccd:3.0.6
```
[ ] Yes
[x ] No
```
> bump chart version

- ccd-claim-migration/src/main/java/uk/gov/hmcts/cmc/ccd/migration/mappers/ClaimMapper.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Claim.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaim.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleResponse.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/mapping/ClaimMapper.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDetailsConverter.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDetailsConverterTest.java
https://tools.hmcts.net/jira/browse/ROC-6642
```
[ ] Yes
[x ] No
```
> ROC-6642: Add intentionToProceedDeadline to claim

- charts/cmc-claim-store/values.preview.template.yaml
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/ClaimState.java
https://tools.hmcts.net/jira/browse/RDM-6144
definition release 1.4.5
```
[ ] Yes
[ ] No
```
> definition release 1.4.5

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CaseMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/ClaimAssert.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/IntentionToProceedService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/IntentionToProceedServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-6715
```
[ ] Yes
[x ] No
```
> ROC-6715: Persist intention to proceed deadline

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CaseEvent.java
- charts/cmc-claim-store/values.preview.template.yaml
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/CreateClaimCitizenTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/InitiatePaymentCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/InitiatePaymentTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/ResumePaymentTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimControllerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-6121
Adding endpoint to create a claim, after initiating / resuming a payment
```
[ ] Yes
[x] No
```
> ROC-6121 Create citizen claim endpoint for ioc

- src/main/resources/staff/templates/email/statesPaid/body.txt
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/StatesPaidEmailContentProviderTest.java
https://tools.hmcts.net/jira/browse/ROC-6612
Remove unnecessary content.
```
[ ] Yes
[x] No
```
> Remove '& 196' from states paid email body

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/InitiatePaymentCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/PaymentsService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legalrep/CreateLegalRepClaimCallbackHandler.java
https://tools.hmcts.net/jira/browse/ROC-6385
Add tracking of app insights events when ioc callbacks are submitted
```
[ ] Yes
[x] No
```
> ROC-6385 Add logging for ioc callbacks

- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/directionsquestionnaire/HearingContentProvider.java
- src/main/resources/citizen/templates/document/claimantDirectionsQuestionnaire.html
- src/main/resources/citizen/templates/document/defendantResponseReceipt.html
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/content/directionsquestionnaire/HearingContentProviderTest.java
https://tools.hmcts.net/jira/browse/ROC-6536
https://tools.hmcts.net/jira/browse/ROC-6429
Change the hearing content provider to include the new CCD fields
```
[ ] Yes
[x] No
```
> ROC 6536 - Hearing Content Provider changes to use the new CCD fields

- build.gradle
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDDirectionOrder.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/DirectionOrderMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/DirectionOrderAssert.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/mapper/DirectionOrderMapperTest.java
- ccd-sample-data/src/main/java/uk/gov/hmcts/cmc/ccd/sample/data/SampleData.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/orders/DirectionOrder.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/DrawOrderCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/DrawOrderCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-6763
ROC-6763: Add hearing court name in direction order
```
[ ] Yes
[ ] No
```
> ROC-6763: Add hearing court name in direction order

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-6244
Release definition 1.4.6
```
[ ] Yes
[ ] No
```
> Release definition 1.4.6

- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportController.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportControllerTest.java
https://tools.hmcts.net/jira/browse/ROC-6784
Add `paid-in-full` as an option for the resend staff notifications endpoint
> ROC-6784 Enable resend staff notifications for PIF

- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-6800
Change bulk print document order for Orders
```
[ ] Yes
[ ] No
```
> ROC-6800: Change bulk print document order for Orders

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
[ROC-6804](https://tools.hmcts.net/jira/browse/ROC-6804)
Bubble up conflict exception received from CCD.
> ROC-6804: Bubble up conflict exception received from CCD

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-6278
Release ccd definition 1.4.7
```
[ ] Yes
[ ] No
```
> Release definition 1.4.7

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/ClaimState.java
https://tools.hmcts.net/jira/browse/ROC-6796
Add proceedsInCaseman new state
```
[ ] Yes
[ ] No
```
> Add proceeds In Case man new state

- charts/cmc-claim-store/values.preview.template.yaml
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/idam/CreateUserRequest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/idam/IdamTestService.java
https://tools.hmcts.net/jira/browse/RDM-6344
Up the domain version to 1.4.9
```
[ ] Yes
[ ] No
```
> Up the domain version to 1.4.9 and add role for creating Idam user

- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/metadata/CaseMetadata.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/CaseMetadataControllerTest.java
https://tools.hmcts.net/jira/browse/ROC-6839
Add intention to proceed deadline to case metadata
> ROC-6839 Add intention to proceed deadline to case metadata

- src/main/resources/application.yml
This PR fixes the url configuration for finish payment,
> Fix finish payment controller url

- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportController.java
https://tools.hmcts.net/jira/browse/ROC-6916
Remove assumption of a single applicant when reissuing an LR claim 
> ROC-6916 Remove assumption of a single applicant when reissuing an LR claim

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-6524
Release definition 1.5.0
```
[ ] Yes
[ ] No
```
> Release definition 1.5.0

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/LinkDefendantToClaimViaAuthenticationTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/IntegrationTestSupportController.java
https://tools.hmcts.net/jira/browse/ROC-6393
```
[ ] Yes
[X] No
```
> ROC-6393: Move params out of url as IIS cannot handle + sign

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/IntentionToProceedService.java
https://tools.hmcts.net/jira/browse/ROC-6872
```
[ ] Yes
[X] No
```
> ROC-6872 Add logging to scheduled job

- build.gradle
- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/ROC-6960
Pass this env variable (https://github.com/hmcts/cmc-integration-tests/blob/master/docker-compose.yml#L530) in claim-store chart
```
[ ] Yes
[ x] No
```
> enable ccd-def url

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-6655
Up the domain version to 1.5.1
```
[ ] Yes
[ ] No
```
> Up the domain version to 1.5.1

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
[ROC-6975](https://tools.hmcts.net/jira/browse/ROC-6975)
This PR fixes the issue where resume and create calls for IOC were not updated the claim data passed.
> ROC-6975: Update claim data in resume and create call

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-6695
Up the domain version to 1.5.2
```
[ ] Yes
[ ] No
```
> Up the domain version to 1.5.2

- charts/cmc-claim-store/requirements.yaml
upgrade to latest citizen-frontend chart version
```
[ ] Yes
[x ] No
```
> update chart dependencies

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/AppInsightsCallbackHandler.java
Add citizen role to have access to raise app insights
```
[ ] Yes
[ ] No
```
> Add citizen role to have access to raise app insights

- Jenkinsfile_CNP
disable auto merging to demo in jenkins build pipeline
```
[ ] Yes
[ x] No
```
> disable auto merging demo

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/GetClaimByExternalReferenceTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
[ROC-7109](https://tools.hmcts.net/jira/browse/ROC-7109)
Fix search legal rep claim by external reference number.
> Fix get claim by external reference no for legal rep

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/ClaimOperation.java
Increase maxAttemps for aat tests
> Increase maxAttemps for aat tests

- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaim.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimantResponse.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleResponse.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ClaimantResponseTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/CommonOperations.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/DirectionsQuestionnaireUtils.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimantResponseServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/utils/ClaimantResponseHelperTest.java
Resolve functional tests
```
[ ] Yes
[ ] No
```
> Resolve functional tests

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/ClaimOperation.java
Decrease max attempts for aat tests retries
> Decrease max attempts for aat tests retries

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
- charts/cmc-claim-store/values.preview.template.yaml
small refactoring to make ccd conditional dependencies
```
[ ] Yes
[x ] No
```
> claim-store chart refactoring

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/PaymentsService.java
Add logs to investigate aat issue
```
[ ] Yes
[x] No
```
> Add logs to investigate aat issue

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/PaymentsService.java
Fix checkstyle issues
```
[ ] Yes
[ ] No
```
> Fix checkstyle issue

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/BaseMockSpringTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/CalendarTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/CourtFinderTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/CreateCitizenClaimCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/CreateClaimCitizenTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/CreateLegalRepClaimCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/InitiatePaymentCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/InitiatePaymentTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/ResumePaymentCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/ResumePaymentTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/legaladvisor/DrawOrderCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/legaladvisor/GenerateOrderCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/BulkPrintStaffNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/CCJStaffNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/ClaimIssuedStaffNotificationEmailContentProviderTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/ClaimantRejectOrgPaymentPlanStaffNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/ClaimantRejectionStaffNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/DefendantResponseStaffNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/PaidInFullStaffNotificationServiceWithEmailServiceRetryTest.java
- src/integrationTest/resources/environment.properties
[ROC-6843](url)
This PR moves tests out of deprecated package, untangles those with database and fix. This is continuation of the refactoring of integration tests.
```
[ ] Yes
[ ] No
```
> ROC-6843: Migrate and fix tests

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/CountyCourtJudgmentService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/CountyCourtJudgmentServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-7141
CCJ cannot be requested when the case is stayed
> ROC-7141: Stayed Claim CCJ

- build.gradle
This PR fixes the CVE-2019-17563
> Fix CVE-2019-17563

- .travis.yml
- build.gradle
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-7222
Fix the resume payment not updating the Draft change.
```
[ ] Yes
[ ] No
```
> ROC-7222-Fix the resume payment not updating the Draft change.

- build.gradle
This excludes the MapperUtil from sonar scan temporarily
```
[ ] Yes
[ ] No
```
> Exclude mapper util

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/ResumePaymentCallbackHandlerTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-7231
ROC-7231: Use existing payment only for successful payment
```
[ ] Yes
[ ] No
```
> ROC-7231: Use existing payment only for successful payment

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/rpa/ClaimIssuedNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/rpa/DefenceResponseNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/rpa/MoreTimeRequestedNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/rpa/RequestForJudgementNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/InterlocutoryJudgmentStaffNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/PaidInFullStaffNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/RejectSettlementAgreementStaffNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/SettlementReachedStaffNotificationServiceTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/StatesPaidStaffNotificationServiceTest.java
[ROC-6843](https://tools.hmcts.net/jira/browse/ROC-6843)
This PR is continuation of the refactoring work to untangle database dependant test and this PR covers specifically rpa and staff services related integration tests only.
> ROC-6843: Migrate and fix tests out of deprecated

- infrastructure/aat.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/ROC-7278
Infrastructure change needed to consistently run functional Tests with IoC on AAT staging slot.
```
[ ] Yes
[ x] No
```
> update infrastructure config

- infrastructure/main.tf
> fix issues

- infrastructure/aat.tfvars
- infrastructure/variables.tf
> revert app setting

- build.gradle
> ROC-7450: Resolve CVE-2020-5398

- charts/cmc-claim-store/Chart.yaml
Bump helm chart version as we have introduced breaking change by removing claim-store db references.
> Bump helm  chart version

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
This PR reverts to old db host urls using load balancer.
> Revert to old urls for db host

- build.gradle
- email-client/build.gradle
- job-scheduler/build.gradle
- job-scheduler/src/main/java/uk/gov/hmcts/cmc/scheduler/services/JobService.java
https://tools.hmcts.net/jira/browse/ROC-7478
Update HMCTS reform logging dependencies to 5.1.1
> ROC-7478 Update reform java logging to 5.1.1

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
- charts/cmc-claim-store/values.preview.template.yaml
- charts/cmc-claim-store/values.yaml
Add conditions to reduce cyclic dependencies on chart level
- [x ] No
> cleanup claimstore chart

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/CreateCitizenClaimCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/CreateLegalRepClaimCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/InitiatePaymentCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/ResumePaymentCallbackHandlerTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/CreateCitizenClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/InitiatePaymentCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legalrep/CreateLegalRepClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/CreateCitizenClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/InitiatePaymentCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-7495
ROC-7495: Update service date on initiate and resume payment callbacks
> ROC-7495: Update service date on initiate and resume payment callbacks

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/CommonOperations.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CalendarController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CallbackController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimantResponseController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CountyCourtJudgmentController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CourtFinderController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/DefendantResponseController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/InterestRatesController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/OffersController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ResponseDeadlineController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/SettlementAgreementController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/UserRolesController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/CaseMetadataController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportController.java
[ROC-7452](https://tools.hmcts.net/jira/browse/ROC-7452)
Update deprecated media types
> ROC-7452: Update deprecated media types

- Jenkinsfile_CNP
N/A
Remove the `enableDockerBuild()` configuration from Jenkins_CNP
> Remove the deprecated `enableDockerBuild()` configuration

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/CreateCitizenClaimCallbackHandler.java
[ROC-7504](https://tools.hmcts.net/jira/browse/ROC-7504)
Update created at time when payment is successfull
> ROC-7504: Update created at time when payment is successful

- build.gradle
- config/checkstyle/checkstyle.xml
N/A
Bump checkstyle tool version and fix configuration
> CVE-2019-10782 bump checkstyle

- charts/cmc-claim-store/values.preview.template.yaml
increase livenessFailureThreshold
- [x ] No
> [WIP]increase livenessFailureThreshold

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/legaladvisor/GenerateOrderCallbackHandlerTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/LegalOrderGenerationDeadlinesCalculator.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/LegalOrderGenerationDeadlinesCalculatorTest.java
https://tools.hmcts.net/jira/browse/ROC-6895
Update deadline days
> ROC-6895: Update deadline days

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBody.java
https://tools.hmcts.net/jira/browse/ROC-7172
Add annotations for json date serialization
> ROC-7172: Add date serialization annotations

- .travis.yml
- Dockerfile
- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
- charts/cmc-claim-store/values.aat.template.yaml
- charts/cmc-claim-store/values.preview.template.yaml
- charts/cmc-claim-store/values.yaml
> Clean up chart. Update docker image

- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/variables.tf
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CallbackController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/CallbackParams.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/CallbackVersion.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/OrderCreator.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/rules/GenerateOrderRule.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/DrawJudgeOrderCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/GenerateOrderCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/rules/GenerateOrderRuleTest.java
Add verisoning to CCD Callbacks
> Versioning CCD Callbacks

- src/main/resources/application.yml
> ROC-7248: Update template version number

- Jenkinsfile_CNP
- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.preview.template.yaml
- charts/cmc-claim-store/values.yaml
> Enable AKS staging

- Jenkinsfile_CNP
disable AKS AAT deployment
- [x ] No
> remove aks aat deployment

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
- charts/cmc-claim-store/values.preview.template.yaml
fixing issues related to postgres
- [x ] No
>  Fixing preview issue

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.yaml
- src/main/resources/bootstrap.yml
> Fix config issues

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.yaml
remove frontend from values and bump version
- [ x] No
> remove frontend

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
- charts/cmc-claim-store/values.preview.template.yaml
upgrade PostgresDB chart version
> upgrade postgres db for PRs

- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/util/MapperUtilTest.java
https://tools.hmcts.net/jira/browse/ROC-7604
Replace deprecated assertions with assertj
> ROC-7604 Refactor deprecated assertions

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.yaml
add DOC_ASSEMBLY_URL to claimstore
- [x ] No
> add DOC_ASSEMBLY_URL

- Jenkinsfile_CNP
- charts/cmc-claim-store/values.aat.template.yaml
JIRA link (if applicable) ###
[AB#791]
> Enable AKS staging deployment

- Jenkinsfile_CNP
- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.yaml
> Fix env vars for test/prod. Enable AAT AKS.

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
- src/main/resources/bootstrap.yml
> Fix milo recipient. Use latest chart java

- Jenkinsfile_CNP
> Disable ithc legacy deployment

- Jenkinsfile_CNP
> Migrate prod to AKS

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/BaseMockSpringTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/orders/BulkPrintSupportController.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/orders/BulkPrintSupportControllerTest.java
Handle Mock mvc failure for filter initialisation
> Handle Mock mvc failure for filter initialisation

- src/main/java/uk/gov/hmcts/cmc/claimstore/events/ccj/CCJStaffNotificationHandler.java
https://tools.hmcts.net/jira/browse/ROC-7377
Added feature toggle to be able to turn on/off the staff email for ccj requested.
> ROC-7377 | added staff email notification toggle

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/PaidInFullStaffNotificationService.java
https://tools.hmcts.net/jira/browse/ROC-7380
decommision staff emails for paid in full
> ROC-7380 - decommission paid in full staff emails

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/StatesPaidStaffNotificationService.java
https://tools.hmcts.net/jira/browse/ROC-7381
decommission staff emails for states paid
> ROC-7381 decommission staff emails for states paid

- src/main/java/uk/gov/hmcts/cmc/claimstore/events/response/MoreTimeRequestedStaffNotificationHandler.java
https://tools.hmcts.net/jira/browse/ROC-7382
decommission the staff notifications for when a defendant requests more time
> ROC-7382 decommission staff emails for more time requested

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/ClaimantRejectionStaffNotificationService.java
https://tools.hmcts.net/jira/browse/ROC-7383
https://tools.hmcts.net/jira/browse/ROC-7386
Added a feature toggle for staff email on/off for claimant rejection.
> Feature/ROC-7386 & ROC-7383 feature toggle for staff email for claimant rejection

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.preview.template.yaml
bump ccd definition importer version to 1.5.10
- [ x] No
> bump ccd definiton importer version

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/ClaimantRejectionStaffNotificationServiceTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/ClaimantRejectionStaffNotificationService.java
https://tools.hmcts.net/jira/browse/ROC-7386
https://tools.hmcts.net/jira/browse/ROC-7383
> ROC-7386 | ROC-7383 | added staff email toggle 

- src/main/java/uk/gov/hmcts/cmc/claimstore/events/offer/AgreementCountersignedStaffNotificationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/offer/RejectSettlementAgreementStaffNotificationHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/offer/AgreementCountersignedStaffNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/offer/RejectSettlementAgreementStaffNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-7388
https://tools.hmcts.net/jira/browse/ROC-7389
added feature toggle for staff emails for settlement agreement accepted or rejected
> Feature/ROC-7388 & ROC-7389 decommission staff email settlement agreement for when settlement accepted or rejected

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/StatesPaidStaffNotificationServiceTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/StatesPaidStaffNotificationService.java
https://tools.hmcts.net/jira/browse/ROC-7381
Decommission emails for states paid
> ROC-7381 | Decommissioning Staff Emails - States Paid

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/DefendantResponseStaffNotificationServiceTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/DefendantResponseStaffNotificationService.java
https://tools.hmcts.net/jira/browse/ROC-7378
https://tools.hmcts.net/jira/browse/ROC-7379
Added a feature toggle to turn on/off the staff emails in case of full admission/part admission/full defence.
> ROC-7378 decommission staff emails on defendant response

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/PaidInFullStaffNotificationServiceTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/PaidInFullStaffNotificationService.java
https://tools.hmcts.net/jira/browse/ROC-7380
Decommission staff emails for paid in full
> ROC-7380 | Decommissioning Staff Email for paid in full

- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DeadlineSupportController.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DeadlineSupportControllerTest.java
https://tools.hmcts.net/jira/browse/ROC-7611
Add option to overwrite dq deadline
> ROC-7611: Add option to overwrite dq deadline

- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/ROC-7655
to decommission ASE AAT resources
- [ x] No
> decommission ase aat

- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
Revert https://github.com/hmcts/cmc-claim-store/pull/1575
> Revert 'decommission ase aat' #1575

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/CCJStaffNotificationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/InterlocutoryJudgmentStaffNotificationService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/CCJStaffNotificationServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/InterlocutoryJudgmentStaffNotificationServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-7387
Decommission re-determination email
> ROC-7387: Decommission re-determination email

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/ROC-6905
https://tools.hmcts.net/jira/browse/ROC-7726
Pipeline didn't like my use of HCL2 syntax; naughty IntelliJ tricked me
> ROC-6905 ROC-7726 Revert use of HCL2 syntax, which the pipeline rejected

- rpa-mapper/src/main/java/uk/gov/hmcts/cmc/rpa/mapper/PaidInFullJsonMapper.java
- rpa-mapper/src/main/java/uk/gov/hmcts/cmc/rpa/mapper/helper/RPAMapperHelper.java
- rpa-mapper/src/test/java/uk/gov/hmcts/cmc/rpa/mapper/helper/RPAMapperHelperTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rpa/PaidInFullNotificationService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/RoboticsSupportControllerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/rpa/PaidInFullNotificationServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-7579
when there is a states paid response and the claimant accepts it then the paid-in-full (PIF) RPA notification should be invoked
> ROC-7579 | states paid response where claimant accepts sends PIF RPA

- infrastructure/demo.tfvars
- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/ROC-7655
decommission ASE PROD
- [x ] No
> decommission ase prod

- build.gradle
[ROC-7707](https://tools.hmcts.net/jira/browse/ROC-7707)
Upgrade payments api client version that contains the change: https://github.com/hmcts/payments-java-client/pull/12
> ROC-7707: Upgrade payments api client version

- src/main/java/uk/gov/hmcts/cmc/claimstore/events/settlement/CountersignSettlementAgreementActionsHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/offer/CountersignSettlementAgreementActionsHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-7740
The email currently sent to the CCBC Inbox, when both parties counter-sign the settlement agreement, will be removed
> ROC 7740 | decommission staff email for countersigned settlement

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.aat.template.yaml
- charts/cmc-claim-store/values.preview.template.yaml
- charts/cmc-claim-store/values.yaml
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/variables.tf
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandlerTest.java
Parent: https://tools.hmcts.net/jira/browse/ROC-6905
This subtask: https://tools.hmcts.net/jira/browse/ROC-7750
Remove the code that toggles auto-cancelling of payments
> ROC-6905 ROC-7750 Remove the auto cancel payments toggle

- infrastructure/variables.tf
N/A
remove client-id variable from infrastructure
> remove client-id variable

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
N/A
upgrade java chart to investigate PR failures on preview
> upgrade java chart

- build.gradle
Fix CVE-2020-7009
Fixed in versions:
-    ">=7.6.2"
-     "<=6.8.8,6.8.8"
-     "<=6.6.2,2.1.0.Beta2"
> Fix CVE-2020-7009

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
upgrade to latest ccd-chart which cleanup utilities pods on Preview cluster after successful completion
- [x ] No
> upgrade ccd-chart

- src/main/java/uk/gov/hmcts/cmc/claimstore/idam/IdamApi.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/UserService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/UserServiceTest.java
Reverting /o/userinfo calls as IDAM not returning roles for some users. causing prod issue.
> Revert user info end point call to idam

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
- charts/cmc-claim-store/values.preview.template.yaml
upgrade to ccd-chart 4.2.2 to fix issues with pipeline
- [ x] No
> upgrade ccd chart

- charts/cmc-claim-store/Chart.yaml
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/ClaimState.java
https://tools.hmcts.net/jira/browse/ROC-7179
https://tools.hmcts.net/jira/browse/ROC-7741
add SETTLEMENT_AGREEMENT_SIGNED CCD state
> ROC-7179 changing case state to settlementAgreementMade

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-8270
> RDM-8270 Upgrade ccd definition version to 1.5.15.3

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/requirements.yaml
upgrade to latest chart-java
- [x ] No
> upgrade base java chart

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-8293
> RDM-8293 Upgrade ccd definition version to 1.5.16

- Jenkinsfile_CNP
remove deprecated pipeline function
- [x ] No
> update jenkins file

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-8494
> RDM-8494 Upgrade ccd definition version to 1.5.17

- build.gradle
> Fix CVE-2020-5407

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-8562
> RDM-8562 Upgrade ccd definition version to 1.5.18

- .travis.yml
- Jenkinsfile_nightly
enable backend functionalTest for Nightly build
- [ x] No
> enable functionalTest in nightly build

- .travis.yml
- Jenkinsfile_nightly
add functional test configuration for nightly tests
- [x ] No
> add config for functional test

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/legaladvisor/DrawOrderCallbackHandlerTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/OrderPostProcessor.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/DrawJudgeOrderCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/DrawOrderCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/GenerateOrderCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementServiceTest.java
https://tools.hmcts.net/jira/browse/ROC-7919
Fix zero size for Direction Order.
> ROC-7919 document size zero diretcion order

- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleResponse.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDetailsConverter.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumePaymentCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDetailsConverterTest.java
- src/test/resources/defendant-response-full-admission.json
- src/test/resources/defendant-response-full-defence.json
https://tools.hmcts.net/jira/browse/ROC-8055
Place ResponseMethod behind feature flag
> ROC-8055: place ResponseMethod behind feature flag

- charts/cmc-claim-store/values.preview.template.yaml
Release notes:
* ROC-7900: Response on paper - Adapt claimant response journeys for full defence.
* ROC-7910: Response on paper - CCD event: review scanned OCON9x form.
> RDM-8809 Upgrade ccd definition version to 1.6.2

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-9032
ROC-8159-Null pointer Exception on Change Contact Details Page
ROC- ROC-8161 OCON toggle
> RDM-9032 bumping ccd version in preview file

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/ROC-8083
https://tools.hmcts.net/jira/browse/RDM-9019
CCD config changes for pcq integration
> RDM-9019 bumping ccd version to 1.6.6

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDApplicant.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/defendant/CCDRespondent.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/CompanyMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/IndividualMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/OrganisationMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/SoleTraderMapper.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/defendant/DefendantPartyMapper.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/party/Company.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/party/Individual.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/party/Organisation.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/party/Party.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/party/SoleTrader.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/utils/PartyUtilsTest.java
- domain-model/src/test/resources/claim-application.json
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleParty.java
- src/test/resources/claim-application.json
- src/test/resources/defendant-response-full-admission.json
- src/test/resources/defendant-response-full-defence.json
- src/test/resources/legal-claim-application.json
Reverts hmcts/cmc-claim-store#1787
> Revert "Roc 8067 pcq aks issue"

- charts/cmc-claim-store/values.preview.template.yaml
- src/test/resources/jackson-serialization-samples/claimant-response.json
https://tools.hmcts.net/jira/browse/ROC-8067
Adding pcqId to test case
> Roc 8067 pcq issue

- domain-model/src/test/resources/claim-application.json
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleParty.java
- src/test/resources/claim-application.json
- src/test/resources/defendant-response-full-admission.json
- src/test/resources/defendant-response-full-defence.json
- src/test/resources/jackson-serialization-samples/claimant-response.json
- src/test/resources/legal-claim-application.json
https://tools.hmcts.net/jira/browse/ROC-8067
pcqId issue changes
> ROC-8067 pcqId issue

- src/main/java/uk/gov/hmcts/cmc/claimstore/events/EventProducer.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/HwfClaimUpdatedEvent.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/PostClaimOrchestrationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/operations/ClaimantOperationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFFullRemissionCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFHalfRemissionCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFMoreInfoRemissionCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFNoRemissionCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFPartRemissionCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/CreateCitizenClaimCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/EventProducerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/PostClaimOrchestrationHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFFullRemissionCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFHalfRemissionCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFMoreInfoRemissionCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFNoRemissionCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFPartRemissionCallbackHandlerTest.java
ROC-7934
Added callbacks to CCD events to notify claimant
> ROC-7934 Added callbacks to CCD events to notify claimant

- audit.json
https://tools.hmcts.net/jira/browse/ROC-8197
security scan fix
> adding audit file changes

- audit.json
https://tools.hmcts.net/jira/browse/ROC-8197
security scan changes
> adding urls to audit.json

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/solicitor/SolicitorPdfTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/idam/IdamApi.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/security/JwtGrantedAuthoritiesConverter.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/UserServiceTest.java
> Openid sonar fix

- charts/cmc-claim-store/Chart.yaml
> Update Chart.yaml  Bump version to 4.1.14

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.preview.template.yaml
- charts/cmc-claim-store/values.yaml
- dependency-check-suppressions.xml
> ccd def version bump

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementService.java
> Resolve Sonar issue

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementService.java
> Sonar issue

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.preview.template.yaml
> Rdm 9523 bump ccd version

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/BaseSubmitClaimTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ClaimPdfTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ClaimantResponseTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/CountyCourtJudgementTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/FeatureTogglesTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/LinkDefendantTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/PaidInFullTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ReDeterminationTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/RespondToClaimTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/SettlementOfferTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/solicitor/SolicitorPdfTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/Retry.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/RetryFailedFunctionalTests.java
> Retry logic for functional tests

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/CountyCourtJudgementTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/RespondToClaimTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/SettlementOfferTest.java
> Roc 8343 functional test fix

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/RespondToClaimTest.java
> nightly functional test fix

- build.gradle
- domain-model/build.gradle
- job-scheduler/build.gradle
Bumps commons-lang3 from 3.10 to 3.11.
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
> Bump commons-lang3 from 3.10 to 3.11

- charts/cmc-claim-store/values.preview.template.yaml
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDM-9849
Change description
Bumping CCD version to 1.16.13
> Rdm 9849 bumping ccd version 1.6.13

- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/PostClaimOrchestrationHandler.java
https://tools.hmcts.net/jira/browse/ROC-8447
Removi PI data from logging during exception
- [ x] No
> Removed event from logging, added claim reference instead

- audit.json
https://tools.hmcts.net/jira/browse/ROC-8565
New Security fixes for nightly build to be fixed
- [x ] No
> added fingerprint

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/paperdefence/PaperResponseLetterService.java
ROC-8580
Add check for organisation while finding court name
> fix for ROC-8580

- src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/ROC-7436
Bespoke order changes
- [ x] No
> Bespoke order template name change after share point upload

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/paperdefence/PaperDefenceLetterBodyMapper.java
https://tools.hmcts.net/jira/browse/ROC-8603
https://tools.hmcts.net/jira/browse/ROC-8603
Null poniter exception when issuing OCON when claimant has not provided phone number
> Fix for null pointer issue

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/ROC-8577
Upgraded Jackson version
Suppressed tomcat dependency issue
> ROC_8577-nightly-build_dependency_issue_fix

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/PaperResponseFullDefenceCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/PaperResponseFullDefenceCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-8626
Paper Response Defense Admissions Journey (Caseworker) - add 'suggested court' for Organisation/Company defendant.
- [N] No
> changes for story ROC-8626

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/paperdefence/IssuePaperDefenceCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/paperresponsetests/IssuePaperDefenceCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-8605
Allow OCON9X Paper response form to be sent to a defendant even after first 19 days expires.
> changes for story ROC-8605

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/paperdefence/PaperDefenceLetterBodyMapper.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBody.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBodyMapper.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBodyMapperTest.java
- src/test/resources/doc-assembly-template.json
https://tools.hmcts.net/jira/browse/ROC-8582
Reconsideration deadline change
> reconsideration change

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/OrderRenderer.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/OrderRendererTest.java
> ROC_8555_bespoke_order_file_name

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/OrderCreator.java
https://tools.hmcts.net/jira/browse/ROC-8646
Bespoke order expert validation bypass
> bypass validation for bespoke

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/ROC-8686
Dependency suppressed. Will be picked up during launch darkly client upgrade
> ROC-8686-Nightly-build-fix

- build.gradle
- domain-model/build.gradle
- email-client/build.gradle
this is the consolidated PR's of other Pr's created by bot.
https://github.com/hmcts/cmc-claim-store/pull/2096
https://github.com/hmcts/cmc-claim-store/pull/2081
https://github.com/hmcts/cmc-claim-store/pull/2087
https://github.com/hmcts/cmc-claim-store/pull/2083
https://github.com/hmcts/cmc-claim-store/pull/2082
https://github.com/hmcts/cmc-claim-store/pull/2078
https://github.com/hmcts/cmc-claim-store/pull/2028
https://github.com/hmcts/cmc-claim-store/pull/2029
https://github.com/hmcts/cmc-claim-store/pull/2015
> consolidated change of all dependency bot PR's for claim store

- build.gradle
> revert flyway dependency to its previous version

- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/CaseMetadataController.java
> update case meta data for functional test

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/paperdefence/PaperDefenceLetterBodyMapper.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/response/PaperResponseReviewedHandler.java
ROC-8740
Introduce a document type as Cherished within 'Paper response review' event.
> changes for story ROC-8740

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-10905
Bumping version to 1.8.9
> bumping version to 1.8.9

- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/PostClaimOrchestrationHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/PaymentsService.java
https://tools.hmcts.net/jira/browse/ROC-8806
> Removed sensitive data (claim data / payment data) logging
> removed sensetive logging

- dependency-check-suppressions.xml
Security vulnerabilities CVE-2021-24122 suppressed 
Security vulnerabilities CVE-2021-24122 suppressed 
> Security vulnerabilities CVE-2021-24122 suppresed

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/legaladvisor/CCDDirectionPartyType.java
- ccd-sample-data/src/main/java/uk/gov/hmcts/cmc/ccd/sample/data/SampleData.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/orders/DirectionParty.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/legaladvisor/DocAssemblyTemplateBodyMapperTest.java
https://tools.hmcts.net/jira/browse/ROC-8668
Bespoke not either party
> bespoke not either party

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/HwFMoreInfoRequiredDocuments.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/config/properties/notifications/EmailTemplates.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/operations/ClaimantOperationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFMiscellaneousCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/HwfClaimNotificationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/content/NotificationTemplateParameters.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/operations/ClaimantOperationServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/HwfClaimNotificationServiceTest.java
ROC-8730
Hwf More Info Required Claimant Notification Mail changes
- [ X] No
> Roc 8730 hwf more info mail

- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimData.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimModificationTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/MoreTimeRequestedOnlineCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/MoreTimeRequestedOnlineCallbackHandlerTest.java
ROC-8585
Request more time by defendant from Citizen Front end triggering email to both claimant and defendant
> ROC-8585 Request More time changes

- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimDataContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/models/ClaimContent.java
- src/main/resources/staff/templates/document/draftClaim.html
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/ClaimDataContentProviderTest.java
**This branch has been merged into** `feature/ROC-8701_Rename_Miscellaneous-HwF`
https://tools.hmcts.net/jira/browse/ROC-8003
> As a claimant
> I want to have a copy of the claim form with the HwF details that I have stored
> so that I can review the details if required in future
> Help with fees : Showing the Claim PDF with watermark

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CaseEvent.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimDataContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFMiscellaneousCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/models/ClaimContent.java
- src/main/resources/staff/templates/document/draftClaim.html
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFMiscellaneousCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/ClaimDataContentProviderTest.java
> https://tools.hmcts.net/jira/browse/ROC-8701
Rename 'Miscellaneous HwF' event to 'Update HwF Number' as part of https://tools.hmcts.net/jira/browse/ROC-8701
> Help With Fees : 'Updated HwF number' event changes

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFFullAndPartRemissionCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
ROC-8893 
Remove anonymous user call while loading claims
> ROC-8893 - remove anonmymous user call

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/MoreTimeRequestedOnlineCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/MoreTimeRequestedOnlineCallbackHandlerTest.java
ROC-8908
more time request online rpa notifications was not getting triggered. this is the fix
> ROC-8908 - RPA notification for More time online

- build.gradle
https://tools.hmcts.net/jira/browse/ROC-8920
Upgraded spring-security-crypto dependency
> nightly-build-dependency-upgrade

- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ClaimControllerTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/OCON9XResponeTest.java
https://tools.hmcts.net/jira/browse/ROC-8840
Functional tests
> Functional tests

- build.gradle
- charts/cmc-claim-store/Chart.yaml
- dependency-check-suppressions.xml
- domain-model/build.gradle
https://tools.hmcts.net/jira/browse/ROC-8878
PR #2101
PR #2126
PR #2137
PR #2147 aka #2180
PR #2148
PR #2154
> claim-store: master bot PR

- README.md
- charts/cmc-claim-store/Chart.yaml
> CCD Chart version upgrade

- build.gradle
https://sonarcloud.io/component_measures?id=uk.gov.hmcts.cmc%3Aclaim-store&pullRequest=2232&metric=new_coverage&view=list
coverage issue
> coverage issue

- build.gradle
- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.yaml
- email-client/build.gradle
- job-scheduler/build.gradle
- rpa-mapper/build.gradle
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/roboticssupport/RoboticsNotificationServiceImpl.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/pilotcourt/PilotCourtServiceTest.java
Reverts hmcts/cmc-claim-store#2232
> Revert "Feature/springboot upgrade 2.4.1"

- charts/cmc-claim-store/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-11642
CCD release
> bump version

- src/main/resources/application.yml
> CourtFinder-URL-Upgrade

- build.gradle
Flyway exception in the AAT AKS deploy fix
> Flyway revert issue

- build.gradle
- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.yaml
- email-client/build.gradle
- job-scheduler/build.gradle
- rpa-mapper/build.gradle
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/roboticssupport/RoboticsNotificationServiceImpl.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/pilotcourt/PilotCourtServiceTest.java
Reverts hmcts/cmc-claim-store#2250
> Revert "spring boot upgrade changes"

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFFullAndPartRemissionCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFMiscellaneousCallbackHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFFullAndPartRemissionCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFMiscellaneousCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-8940
https://tools.hmcts.net/jira/browse/ROC-8940
> ROC-8940 changes

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.yaml
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/GenerateOrderCallbackHandlerTest.java
Master build is broken due to health check on MTA which is disabled
> MTA health disabled - Master build fix

- charts/cmc-claim-store/values.aat.template.yaml
> odic issuer changed to aat2

- charts/cmc-claim-store/values.preview.template.yaml
> RDM-12394-bumping-ccd-ver-to-1.10.5

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CCDCase.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/ClaimMapper.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/ClaimData.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimData.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimDataForHwF.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFFullAndPartRemissionCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFMiscellaneousCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/CreateCitizenClaimCallbackHandler.java
- src/test/resources/claim-application-hwf.json
merge hwf outstanding amount into pba v2 - hwf common branch
> ROC-9125 Hwf Outstanding amount changes

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFRecalculateInterestCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/PaymentsService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/HWFRecalculateInterestCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/PaymentsServiceTest.java
> New claim fees changes

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
> Changes for fixing the bug related to court filter

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/statetransition/StateTransitions.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/statetransition/StateTransitionsTest.java
> Changes to include paper response for state transition

- build.gradle
https://tools.hmcts.net/jira/browse/ROC-9291
Bintray has been decommisioned now and all public hmcts artifact moved to  jitpack.io. 
https://hmcts-reform.slack.com/files/T1L0WSW9F/F01STNP6666?origin_team=T1L0WSW9F&origin_channel=Psearch
> updated gradle dependency url

- build.gradle
https://tools.hmcts.net/jira/browse/ROC-9291
> Excluded HWFcallBackHandler classes

- security.sh
> Security scan failure -- Test url already have / in the end

- README.md
- security.sh
Green PR
https://build.platform.hmcts.net/blue/organizations/jenkins/HMCTS_Nightly_CMC%2Fcmc-claim-store/detail/PR-2436/4/pipeline/
> Testing nightly pipeline

- infrastructure/main.tf
> added db v11 in demo

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/ROC-9194
> env sync up

- Jenkinsfile_CNP
Disable sync up as it is blocking postgress db upgrade in demo, perftest and ithc by overriding the changes from master
- [ x] No
> Disable sync up as it is blocking few db upgrade stories

- dependency-check-suppressions.xml
Suppressed the error caused in dependency check
> Claim-store nightly build dependency check

- dependency-check-suppressions.xml
> nightly build Dependency fix

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/ROC-8994
> added db v11 for perf branch

- charts/cmc-claim-store/values.preview.template.yaml
> PR failures : idam oidc url updated

- build.gradle
> fix elastic jar vulnerability

- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/ROC-9392
> fortify scan changes

- rpa-mapper/src/main/java/uk/gov/hmcts/cmc/rpa/mapper/MoreTimeRequestedJsonMapper.java
- rpa-mapper/src/test/java/uk/gov/hmcts/cmc/rpa/mapper/MoreTimeRequestedJsonMapperTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/rpa/MoreTimeRequestedNotificationServiceTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/rpa/MoreTimeRequestedNotificationService.java
https://tools.hmcts.net/jira/browse/ROC-8922
Updated the actual more time requested date time logic
> Update Send RPA support controller

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/CaseMetadataController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/ClaimIssueService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/jobs/cron/ClaimIssueJob.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/ClaimIssueServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/jobs/cron/ClaimIssueJobTest.java
https://tools.hmcts.net/jira/browse/ROC-9191
> reissue claim logic

- infrastructure/main.tf
- infrastructure/state.tf
> creating new database

- security.sh
Fix security scan nighhtly build
> removing zap cli from security file

- charts/cmc-claim-store/values.preview.template.yaml
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CFTS-783
bump ccd version
> Bump ccd version

- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/response/PaperResponseReviewedHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/response/PaperResponseReviewedHandlerTest.java
https://tools.hmcts.net/jira/browse/ROC-9492
Email notification won't be triggered if the scanned document type is coversheet
> Email for coversheet removed from paper response review event

- infrastructure/state.tf
> Adding azuread provider to fix terraform show error

- charts/cmc-claim-store/values.preview.template.yaml
> bump ccd definition importer to 1.10.20

- dependency-check-suppressions.xml
> suppress dependency - fix nightly

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.preview.template.yaml
The pr cover hwf release updates in definition importer and the role assignment service changes
> HWF release update

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/ResumeHelpWithFeeClaimSubmissionCallbackHandler.java
> Update ResumeHelpWithFeeClaimSubmissionCallbackHandler.java with hwf update

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/legaladvisor/CCDHearingDurationType.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/orders/HearingDurationType.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/DrawJudgeOrderCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-512
Added new CCDHearingDurationType field of two and a half hours
> CIV-512: Added new CCD hearing duration type

- infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CIV-1167
updated state.tf to include azurerm send grid subscription as per platops recommendations
> CIV-1167 : updated state.tf to include azurerm send grid subscription

- Jenkinsfile_CNP
Free resources in preview cluster after pr turns green.
More info : https://github.com/hmcts/cnp-jenkins-library/pull/801
> Clear helm release on successful build

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CIV-1262
Temp suppressed OWASP warnings. 
The following tickets will deal with the OWASP dependency issues:
- https://tools.hmcts.net/jira/browse/CIV-795
- https://tools.hmcts.net/jira/browse/CIV-670
> CIV-1262 : temp suppressed owasp warnings

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CIV-1337
Temporarily suppress security vulnerability
> CIV-1337 : temporarily suppress security vulnerability

- charts/cmc-claim-store/Chart.yaml
https://tools.hmcts.net/jira/browse/CIV-1253
Updated deprecated chart configuration
> CIV-1253 : updated deprecated chart configuration

- Jenkinsfile_nightly
> Enable security scan in Jenkinsfile_nightly

- Dockerfile
- docker/database/Dockerfile
https://tools.hmcts.net/jira/browse/CIV-1515
> Forify scan fix: Docker file should not be run with sudo permissions

- charts/cmc-claim-store/Chart.yaml
https://tools.hmcts.net/jira/browse/CIV-1494
Upgraded Base helm charts
> CIV-1494 : upgraded base helm charts

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CIV-1653
suppressed dependency vulnerabilities
> CIV-1653 : suppressed dependency vulnerabilities

- build.gradle
- config/checkstyle/checkstyle.xml
- src/test/java/uk/gov/hmcts/cmc/claimstore/test/utils/DataFactory.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/test/utils/FileReaderUtils.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/test/utils/JsonParserUtils.java
https://tools.hmcts.net/jira/browse/CIV-1799
Added the ability to generate test data from JSON
> CIV-1799 : added the ability to generate test data from JSON

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/legaladvisor/CCDHearingDurationType.java
- charts/cmc-claim-store/values.preview.template.yaml
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/orders/HearingDurationType.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/DrawJudgeOrderCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-1168
Manual rollback
> CIV-1168 : manual rollback

- config/owasp/suppressions.xml
- launch-darkly-client/build.gradle
> CIV-2993: Fix CVE-2022-25647

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/directionsquestionnaire/CCDDirectionsQuestionnaire.java
> ignore unknown fields

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/directionsquestionnaire/CCDDirectionsQuestionnaire.java
- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/DirectionsQuestionnaireMapper.java
- ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/DirectionsQuestionnaireAssert.java
- charts/cmc-claim-store/Chart.yaml
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/directionsquestionnaire/DeterminationWithoutHearingQuestions.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/directionsquestionnaire/DirectionsQuestionnaire.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/directionsquestionnaire/VulnerabilityQuestions.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimantResponse.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleDirectionsQuestionnaire.java
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleResponse.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ClaimantResponseTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/ClaimOperation.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/documents/DefendantResponseReceiptServiceIT.java
- src/integrationTest/resources/documents/expectedDefendantResponseWithNoHearingSupportReceipt.html
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/directionsquestionnaire/HearingContentProvider.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/models/HearingContent.java
- src/main/resources/citizen/templates/document/claimantDirectionsQuestionnaire.html
- src/main/resources/citizen/templates/document/defendantResponseReceipt.html
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/content/directionsquestionnaire/HearingContentProviderTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/EventProducerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/security/JwtGrantedAuthoritiesConverterTest.java
CIV-2104 and CIV-1418, CIV-1381 and CIV-2428
> feat: release for CIV-2104 and CIV-1418, CIV-1381 and CIV-2428

- charts/cmc-claim-store/values.preview.template.yaml
> Bump CCD definition version to 1.10.30

- src/main/resources/application.yml
> claimant respond to order email template change

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CIV-4735
> fix master - supress CVE-2022-25857

- build.gradle
- config/owasp/suppressions.xml
- launch-darkly-client/build.gradle
> Fix CVE-2022-25857

- build.gradle
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/BreathingSpace.java
- domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Payment.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/config/JacksonConfiguration.java
CIV-4743
Fix deprecation warnings
> CIV-4743: Fix deprecation warnings

- build.gradle
- config/owasp/suppressions.xml
- domain-model/build.gradle
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/AddressTest.java
- domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/TheirDetailsTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/ScheduledStateTransitionContentProviderTest.java
https://tools.hmcts.net/jira/browse/CIV-4864
> Fix/civ 4864 CVE 2020 25638

- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/InitiatePaymentTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/exceptions/UnprocessableEntityException.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
> CIV-4988: POST CountyCourtJudgmentController

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/courtfinder/CourtFinderService.java
[CIV-4997](https://tools.hmcts.net/jira/browse/CIV-4997)
Fix Nullpointerexception
> feat: GET CourtFinderController/searchByPostcode - count 197 (CIV-4997)

- build.gradle
- config/owasp/suppressions.xml
> Fix for CVE-2022-23181

- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.aat.template.yaml
- charts/cmc-claim-store/values.preview.template.yaml
- charts/cmc-claim-store/values.yaml
https://tools.hmcts.net/jira/browse/CIV-6617
> remove bitnami dependency

- config/owasp/suppressions.xml
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ClaimantResponseTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/ReDeterminationTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/SettlementOfferTest.java
https://tools.hmcts.net/jira/browse/CIV-6687
> disable tests

- build.gradle
- config/owasp/suppressions.xml
> Fix CVE-2021-30639

- config/owasp/suppressions.xml
> Fixed CVEs cleanup

- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDetailsConverter.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDetailsConverterTest.java
https://tools.hmcts.net/jira/browse/CIV-4999
> CIV-4999: GET ClaimController/getBySubmitterId - count 162

- charts/cmc-claim-store/Chart.yaml
- config/owasp/suppressions.xml
CIV-4873
The CVE-2021-42340 is resolved already so removing this from suppressions.
> CIV-4873: Fix for CVE-2021-42340

- build.gradle
- config/owasp/suppressions.xml
> CIV-4876: Fix CVE-2021-44832

- config/owasp/suppressions.xml
> CIV-4875 Fix for CVE-2021-44228

- README.md
- build.gradle
- config/owasp/suppressions.xml
- settings.gradle
Upgrade to 8.0.1 dependency check plugin
> CIV-6997: Fix master pipelines

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
> Fix: Code cleanup

- config/owasp/suppressions.xml
> add suppression

- build.gradle
- charts/cmc-claim-store/Chart.yaml
- config/owasp/suppressions.xml
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
CIV-7070
Upgrade springboot version
> CIV-7070 Upgrade springboot version

- config/owasp/suppressions.xml
> Fixed CVEs

- Dockerfile
- config/owasp/suppressions.xml
> Fix pipelines

- build.gradle
- config/owasp/suppressions.xml
- job-scheduler/build.gradle
CIV-4887
Fix for CVE-2022-31197
> CIV-4887: Fix for CVE-2022-31197

- build.gradle
- config/owasp/suppressions.xml
- launch-darkly-client/build.gradle
> CIV-6101: Fix CVE-2022-41854

- config/owasp/suppressions.xml
> add suppressions

- build.gradle
- config/owasp/suppressions.xml
> CIV-8367: Fix CVE-2023-20860

- README.md
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandler.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandlerTest.java
CIV-5002
Resolve Feign exception
> CIV-5002 resolve Feign exception

- config/owasp/suppressions.xml
> add supression

- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/ClaimIssueService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/jobs/cron/ClaimIssueJob.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/ClaimIssueServiceTest.java
> CIV-8537: automate unstuck claims

- config/owasp/suppressions.xml
- infrastructure/db.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CIV-505
Adding v14 postgresql server.
> adding v14 postgresql server

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/DirectionsQuestionnaireService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/TheirDetailsHelper.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/DirectionsQuestionnaireServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-9970
> CIV-9970 update pilot court logic

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/DummyBulkPrintService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/PrintService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/PinOrchestrationService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/breathingspace/BreathingSpaceLetterService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDataExtractorUtils.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/DummyBulkPrintServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/PinOrchestrationServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/breathingspace/BreathingSpaceLetterServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-10327
> CIV-10327 add bulk print service changes

- build.gradle
https://tools.hmcts.net/jira/browse/CIV-10327
> ignore transitive dependencies

- Jenkinsfile_CNP
> fix master

- Jenkinsfile_CNP
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/SecuredDocumentManagementService.java
https://tools.hmcts.net/jira/browse/CIV-9920
increase max attempts and delay
> CIV-9920 increase max attempts and delay

- .github/CODEOWNERS
- renovate.json
enabledManagers has been deprecated. Updated renovate.json and CODEOWNERS file according to this guide:
https://hmcts.github.io/cloud-native-platform/guides/automated-dependency-updates.html
> Update Renovate Config

- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/transfercase/TransferCaseStateService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportControllerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/transfercase/TransferCaseStateServiceTest.java
https://tools.hmcts.net/jira/browse/SNI-4686
> SNI-4686 allow case transfer of cases when given a state

- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/DrawJudgeOrderCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/GenerateOrderCallbackHandlerTest.java
> CIV-0000 update tests to fix master

- charts/cmc-claim-store/Chart.yaml
- config/owasp/suppressions.xml
> CIV-0000 Add suppression

- infrastructure/main.tf
- infrastructure/state.tf
- infrastructure/variables.tf
> CIV-10543 changes for master

- infrastructure/main.tf
- infrastructure/state.tf
- infrastructure/variables.tf
Reverts hmcts/cmc-claim-store#2798
> Revert "CIV-10543 changes for master"

- infrastructure/main.tf
removing force_user_permissions_trigger
> CIV-0000 removing force_user_permissions_trigger

- infrastructure/main.tf
Adding force_user_permissions_trigger
> CIV-0000 adding force_user_permissions_trigger

- infrastructure/main.tf
> CIV-0000 remove v10 db

- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDataExtractorUtils.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDataExtractorUtilsTest.java
https://tools.hmcts.net/jira/browse/CIV-11769
OCMC - transfer pack entry not appearing in send letter DB when defendant responds online
> CIV-11769 Transfer-pack entry not appearing for same recipients within 1 hour of Generate order

- infrastructure/main.tf
Reverts hmcts/cmc-claim-store#2833
> CIV-0000 removing v11 for fixing master Revert 

- infrastructure/main.tf
> CIV-0000 removing v11

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSCCI-60
Reduce CVEs
> DTSCCI-060 Reduce CVEs

- charts/cmc-claim-store/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSCCI-201
> DTSCCI-201 upgrading ccd chart

- build.gradle
- ccd-adapter/build.gradle
- ccd-sample-data/build.gradle
- domain-model/build.gradle
- email-client/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
- job-scheduler/build.gradle
- rpa-mapper/build.gradle
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/config/FeignErrorDecoder.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/citizen/SettlementOfferTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/idam/IdamTestApi.java
https://tools.hmcts.net/jira/browse/DTSCCI-217
Upgrades that can be done before spring boot 3 in order to reduce the size of spring boot update
> DTSCCI 217 upgrades before spring boot 3 

- build.gradle
- src/main/resources/application.yml
Pull request to fix errors showing in master pipeline. 
> Fix pipeline

- build.gradle
DTSCCI-490
remove deprecated property volume lib
> DTSCCI-490 remove deprecated property volume lib

- Jenkinsfile_CNP
- build.gradle
- src/contractTest/java/uk/gov/hmcts/cmc/claimstore/api/provider/CmcClaimantApiProviderTest.java
- src/contractTest/java/uk/gov/hmcts/cmc/claimstore/api/provider/CmcDefendantApiProviderTest.java
- src/contractTest/java/uk/gov/hmcts/cmc/claimstore/api/provider/CmcDefendantLinkedApiProviderTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-508
> DTSCCI-508 adding provider contract test

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
https://tools.hmcts.net/jira/browse/DTSCCI-257
> DTSCCI-257 Log preferred court

- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
https://tools.hmcts.net/jira/browse/DTSCCI-257
> DTSCCI-257 Re-add preferredDQPilotCourt

- Jenkinsfile_CNP
- src/contractTest/java/uk/gov/hmcts/cmc/claimstore/api/provider/GetClaimsContractConfig.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/UserAuthorisationTokenService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/UserInfoService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/UserService.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/UserAuthorisationTokenServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/UserInfoServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/UserServiceTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-242
Fix @cacheable self invocation
> Fix @cacheable self invocation

- lib/applicationinsights.json
https://tools.hmcts.net/jira/browse/DTSCCI-916
Reducing application insights by sampling health checks.
> DTSCCI-916 Reduce Application Insights

- ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/CaseEvent.java
- charts/cmc-claim-store/Chart.yaml
- charts/cmc-claim-store/values.preview.template.yaml
- config/owasp/suppressions.xml
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/BaseTest.java
- src/aat/resources/environment.properties
- src/contractTest/java/uk/gov/hmcts/cmc/claimstore/api/provider/GetClaimsContractConfig.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/CreateCitizenClaimCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/CreateClaimCallbackHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ioc/CreateLegalRepClaimCallbackHandlerTest.java
- src/integrationTest/resources/environment.properties
- src/main/java/uk/gov/hmcts/cmc/claimstore/constants/ResponseConstants.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/exceptions/ClaimCreationDisabledException.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CallbackHandlerFactory.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/CallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/CreateClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/CreateCitizenClaimCallbackHandler.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legalrep/CreateLegalRepClaimCallbackHandler.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/CreateClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/ioc/CreateCitizenClaimCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legalrep/CreateLegalRepClaimCallbackHandlerTest.java
- src/test/resources/environment.properties
> DTSCCI-1530 feature flag for OCMC claims creation

- build.gradle
- config/owasp/suppressions.xml
- domain-sample-data/src/main/java/uk/gov/hmcts/cmc/domain/models/sampledata/SampleClaimData.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/solicitor/SolicitorPdfTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/solicitor/SolicitorSubmitClaimTest.java
- src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/TestData.java
- src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimModificationTest.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseApi.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CaseRepository.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
- src/main/java/uk/gov/hmcts/cmc/claimstore/services/pilotcourt/PilotCourtService.java
- src/main/java/uk/gov/hmcts/reform/fees/client/model/FeeLookupResponseDto.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimControllerTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ClaimServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
- src/test/java/uk/gov/hmcts/cmc/claimstore/services/pilotcourt/PilotCourtServiceTest.java
Reverts hmcts/cmc-claim-store#3298
> Revert "DTSCCI-2597 Fix concurrency issue in ocmc and get rid old legal rep api calls"
